# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'functionmain.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import QButtonGroup
from PyQt5.QtGui import QCursor
from components.mySwitch import MySwitch

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet("background:black;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("background-image : url(images/background.png);")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        
        self.label_10 = QtWidgets.QLabel(self.centralwidget) #logo
        self.label_10.setMaximumSize(QtCore.QSize(540, 95))
        self.label_10.setStyleSheet("background:blue")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("images/logoo.png"))
        self.label_10.setScaledContents(False)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10) #horizontal 0
        
        self.horizontalLayout_logo = QtWidgets.QHBoxLayout()
        self.horizontalLayout_logo.setSpacing(0)
        self.horizontalLayout_logo.setObjectName("HorizontalLayout_logo")
        
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget) #go back to menu
        self.pushButton_6.setMinimumSize(QtCore.QSize(80,80))
        self.pushButton_6.setMaximumSize(QtCore.QSize(80,80))
        self.pushButton_6.setStyleSheet("""
                                        QPushButton{
                                                background-color: black;
                                                color:white;
                                                border-radius:10px;
                                        }
                                        QPushButton:hover{
                                                background-color: #00BDFE;
                                        }
                                """)
        self.pushButton_6.setDefault(True)
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout_logo.addWidget(self.pushButton_6)
        
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_logo.addItem(spacerItem) 
        
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget) 
        self.pushButton_7.setMinimumSize(QtCore.QSize(80,80))
        self.pushButton_7.setMaximumSize(QtCore.QSize(80,80))
        self.pushButton_7.setStyleSheet("""
                                        QPushButton{
                                                background-color: #00BDFE;
                                                color:white;
                                                border-radius:10px;
                                        }
                                        QPushButton:hover{
                                                background-color: #00BDFE;
                                        }
                                """)
        self.pushButton_7.setDefault(True)
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout_logo.addWidget(self.pushButton_7) 
        
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_logo.addItem(spacerItem1) 

        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget) #gotosettings
        self.pushButton_8.setMinimumSize(QtCore.QSize(80,80))
        self.pushButton_8.setMaximumSize(QtCore.QSize(80,80))
        self.pushButton_8.setStyleSheet("""
                                        QPushButton{
                                                background-color: black;
                                                color:white;
                                                border-radius:10px;
                                        }
                                        QPushButton:hover{
                                                background-color: #00BDFE;
                                        }
                                """)
        self.pushButton_8.setDefault(True)
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout_logo.addWidget(self.pushButton_8) 
        
        self.horizontalLayout_logo.addItem(spacerItem)
        
        self.pushButton_search = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_search.setMinimumSize(QtCore.QSize(80,80))
        self.pushButton_search.setMaximumSize(QtCore.QSize(80,80))
        self.pushButton_search.setStyleSheet("""
                                        QPushButton{
                                                background-color: black;
                                                color:white;
                                                border-radius:10px;
                                        }
                                        QPushButton:hover{
                                                background-color: #00BDFE;
                                        }
                                """)
        self.pushButton_search.setDefault(True)
        self.pushButton_search.setFlat(True)
        self.pushButton_search.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_search.setObjectName("PushButton_search")
        self.horizontalLayout_logo.addWidget(self.pushButton_search)
        
        self.horizontalLayout_logo.addItem(spacerItem)
        
        self.horizontalLayout_logo.setStretch(0,10)
        self.horizontalLayout_logo.setStretch(1,1)
        self.horizontalLayout_logo.setStretch(2,9)
        self.horizontalLayout_logo.setStretch(3,1)
        self.horizontalLayout_logo.setStretch(4,9)
        self.horizontalLayout_logo.setStretch(5,1)
        self.horizontalLayout_logo.setStretch(6,9)
        self.horizontalLayout_logo.setStretch(8,10)
        
        self.horizontalLayout_5.addLayout(self.horizontalLayout_logo) #horizontal -2
        
        
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3) #horizontal -3
        
        self.label_23 = QtWidgets.QLabel(self.centralwidget) #tanda window
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK TC")
        font.setPointSize(20)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color:#707070;")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_5.addWidget(self.label_23) #horizontal -4
        
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4) #horizontal - 5
        
        self.ppe = QtWidgets.QPushButton(self.centralwidget)#logo
        self.ppe.setMaximumSize(QtCore.QSize(60, 60))
        self.ppe.setAutoFillBackground(False)
        self.ppe.setStyleSheet("border-radius: 15px;")
        self.ppe.setText("")
        self.ppe.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/Group 104.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ppe.setIcon(icon)
        self.ppe.setIconSize(QtCore.QSize(60, 60))
        self.ppe.setObjectName("ppe")
        
        self.horizontalLayout_5.addWidget(self.ppe) #horizontal - 6
        
        
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5) #horizontal - 7
        
        self.horizontalLayout_5.setStretch(0, 3)
        self.horizontalLayout_5.setStretch(1, 80)
        self.horizontalLayout_5.setStretch(2, 10)
        self.horizontalLayout_5.setStretch(3, 1)
        self.horizontalLayout_5.setStretch(4, 1)
        self.horizontalLayout_5.setStretch(5, 1)
        self.horizontalLayout_5.setStretch(6, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background:#121E28;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("color:white;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_0 = QtWidgets.QPushButton(self.frame) #settings 1 and 2
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_0.setStyleSheet("color:white;")
        self.pushButton_0.setObjectName("pushButton_0") #gong neng
        self.verticalLayout.addWidget(self.pushButton_0)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("color:white;background:#3A3C41;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setAutoFillBackground(False)
        self.pushButton_4.setStyleSheet("color:white;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)

        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setAutoFillBackground(False)
        self.pushButton_5.setStyleSheet('color: white')
        self.verticalLayout.addWidget(self.pushButton_5)

        self.pushButtonReset = QtWidgets.QPushButton(self.frame)
        self.pushButtonReset.setText('Factory Reset')
        self.pushButtonReset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonReset.setFont(font)
        self.pushButtonReset.setAutoFillBackground(False)
        self.pushButtonReset.setStyleSheet('color: white')
        self.verticalLayout.addWidget(self.pushButtonReset, alignment = QtCore.Qt.AlignBottom)

        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background:black")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem10 = QtWidgets.QSpacerItem(1058, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem10) #1
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setSpacing(0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        
        self.monday = QtWidgets.QFrame(self.frame_2)
        self.monday.setStyleSheet("#monday{border: 2px  solid #757475;}")
        self.monday.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.monday.setFrameShadow(QtWidgets.QFrame.Raised)
        self.monday.setObjectName("monday")
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout(self.monday)
        self.horizontalLayout_54.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_54.setSpacing(0)
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setContentsMargins(-1, -1, -1, 8)
        self.verticalLayout_23.setSpacing(8)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_26 = QtWidgets.QLabel(self.monday)
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 46))
        font = QtGui.QFont()
        font.setPointSize(16)
        fontTitle = QtGui.QFont()
        fontTitle.setPointSize(23)
        self.label_26.setFont(fontTitle)
        self.label_26.setStyleSheet("background:#3A3C41;color:white;")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_23.addWidget(self.label_26)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(3, -1, 3, -1)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")

        self.labelMonday = QtWidgets.QLabel(self.monday)
        self.labelMonday.setFont(font)
        self.labelMonday.setStyleSheet('color:white; padding-left: 10px;')
        self.labelMonday.setText('Set Time Table:  ')

        self.horizontalLayout_6.addWidget(self.labelMonday)

        self.setTimeMonday = QtWidgets.QPushButton(self.monday)
        self.setTimeMonday.setFont(font)
        self.setTimeMonday.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.setTimeMonday.setText('Choose')
        self.setTimeMonday.setMinimumSize(QtCore.QSize(120,30))
        self.setTimeMonday.setMaximumSize(QtCore.QSize(120,30))
        self.setTimeMonday.setStyleSheet("""
            QPushButton{
                background-color: #4277BD;
                color: white;
                border-radius: 10px;
                margin-right: 10px
            }
            QPushButton:hover{
                background-color: #499DD0;
                border-radius: 10px;
            }
        """)
        self.setTimeMonday.setObjectName('setTimeMonday')
        self.horizontalLayout_6.addWidget(self.setTimeMonday)
        self.verticalLayout_23.addLayout(self.horizontalLayout_6)
        self.verticalLayout_23.setStretch(0, 12)
        self.horizontalLayout_54.addLayout(self.verticalLayout_23)
        self.horizontalLayout_25.addWidget(self.monday)
        
        self.tuessday = QtWidgets.QFrame(self.frame_2)
        self.tuessday.setStyleSheet("#tuessday{border: 2px  solid #757475;}")
        self.tuessday.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tuessday.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tuessday.setObjectName("tuessday")
        self.horizontalLayout_56 = QtWidgets.QHBoxLayout(self.tuessday)
        self.horizontalLayout_56.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_56.setSpacing(0)
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setContentsMargins(-1, -1, -1, 8)
        self.verticalLayout_24.setSpacing(8)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_36 = QtWidgets.QLabel(self.tuessday)
        self.label_36.setMaximumSize(QtCore.QSize(16777215, 46))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_36.setFont(fontTitle)
        self.label_36.setStyleSheet("background:#3A3C41;color:white;")
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_24.addWidget(self.label_36)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(3, -1, 3, -1)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")

        self.labelTuesday = QtWidgets.QLabel(self.tuessday)
        self.labelTuesday.setText('Set Time Table: ')
        self.labelTuesday.setFont(font)
        self.labelTuesday.setObjectName('Label Tuesday')
        self.labelTuesday.setStyleSheet('color:white; padding-left: 10px ')

        self.horizontalLayout_9.addWidget(self.labelTuesday)
        
        self.setTimeTuesday = QtWidgets.QPushButton(self.tuessday)
        self.setTimeTuesday.setFont(font)
        self.setTimeTuesday.setObjectName('setTimeTuesday')
        self.setTimeTuesday.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.setTimeTuesday.setText('Choose')
        self.setTimeTuesday.setMinimumSize(QtCore.QSize(120,30))
        self.setTimeTuesday.setMaximumSize(QtCore.QSize(120,30))
        self.setTimeTuesday.setStyleSheet( """
            QPushButton{
                background-color: #4277BD;
                color: white;
                border-radius: 10px;
                margin-right: 10px
            }
            QPushButton:hover{
                background-color: #499DD0;
                border-radius: 10px;
            }
        """)
        
        self.horizontalLayout_9.addWidget(self.setTimeTuesday)
        
        self.verticalLayout_24.addLayout(self.horizontalLayout_9)
        self.verticalLayout_24.setStretch(0, 12)
        self.horizontalLayout_56.addLayout(self.verticalLayout_24)
        self.horizontalLayout_25.addWidget(self.tuessday)
        
        self.wednesday = QtWidgets.QFrame(self.frame_2)
        self.wednesday.setStyleSheet("#wednesday{border: 2px  solid #757475;}")
        self.wednesday.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wednesday.setFrameShadow(QtWidgets.QFrame.Raised)
        self.wednesday.setObjectName("wednesday")
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout(self.wednesday)
        self.horizontalLayout_57.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_57.setSpacing(0)
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setContentsMargins(-1, -1, -1, 8)
        self.verticalLayout_26.setSpacing(8)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_37 = QtWidgets.QLabel(self.wednesday)
        self.label_37.setMaximumSize(QtCore.QSize(16777215, 46))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_37.setFont(fontTitle)
        self.label_37.setStyleSheet("background:#3A3C41;color:white;")
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_26.addWidget(self.label_37)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(3, -1, 3, -1)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        
        self.labelWednesday = QtWidgets.QLabel(self.wednesday)
        self.labelWednesday.setObjectName('labelWednesday')
        self.labelWednesday.setText('Set Time Table: ')
        self.labelWednesday.setFont(font)
        self.labelWednesday.setStyleSheet('color:white; padding-left: 10px')
        self.horizontalLayout_10.addWidget(self.labelWednesday)
        
        self.setTimeWednesday = QtWidgets.QPushButton(self.wednesday)
        self.setTimeWednesday.setObjectName('setTimeWednesday')
        self.setTimeWednesday.setMaximumSize(QtCore.QSize(120,30))
        self.setTimeWednesday.setMinimumSize(QtCore.QSize(120,30))
        self.setTimeWednesday.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.setTimeWednesday.setText('Choose')
        self.setTimeWednesday.setFont(font)
        self.setTimeWednesday.setStyleSheet("""
            QPushButton{
                background-color: #4277BD;
                color: white;
                border-radius: 10px;
                margin-right: 10px
            }
            QPushButton:hover{
                background-color: #499DD0;
                border-radius: 10px;
            }
        """)
        self.horizontalLayout_10.addWidget(self.setTimeWednesday)
        self.verticalLayout_26.addLayout(self.horizontalLayout_10)
        self.verticalLayout_26.setStretch(0, 12)
        self.horizontalLayout_57.addLayout(self.verticalLayout_26)
        self.horizontalLayout_25.addWidget(self.wednesday)
        self.verticalLayout_6.addLayout(self.horizontalLayout_25)
        
        self.horizontalLayout_63 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_63.setSpacing(0)
        self.horizontalLayout_63.setObjectName("horizontalLayout_63")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setSpacing(0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        
        self.thursday = QtWidgets.QFrame(self.frame_2)
        self.thursday.setStyleSheet("#thursday{border: 2px  solid #757475;}")
        self.thursday.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.thursday.setFrameShadow(QtWidgets.QFrame.Raised)
        self.thursday.setObjectName("thursday")
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout(self.thursday)
        self.horizontalLayout_58.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_58.setSpacing(0)
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setContentsMargins(-1, -1, -1, 8)
        self.verticalLayout_27.setSpacing(8)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_38 = QtWidgets.QLabel(self.thursday)
        self.label_38.setMaximumSize(QtCore.QSize(16777215, 46))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_38.setFont(fontTitle)
        self.label_38.setStyleSheet("background:#3A3C41;color:white;")
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_27.addWidget(self.label_38)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(3, -1, 3, -1)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        
        self.labelThursday = QtWidgets.QLabel(self.thursday)
        self.labelThursday.setFont(font)
        self.labelThursday.setStyleSheet('color:white; padding-left: 10px')
        self.labelThursday.setText('Set Time Table: ')
        self.labelThursday.setObjectName('Label Thursday')
        
        self.horizontalLayout_12.addWidget(self.labelThursday)
        
        self.setTimeThursday = QtWidgets.QPushButton(self.thursday)
        self.setTimeThursday.setObjectName('setTimeThursday')
        self.setTimeThursday.setMinimumSize(QtCore.QSize(120,30))
        self.setTimeThursday.setMaximumSize(QtCore.QSize(120,30))
        self.setTimeThursday.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.setTimeThursday.setText('Choose')
        self.setTimeThursday.setFont(font)
        self.setTimeThursday.setStyleSheet("""
            QPushButton{
                background-color: #4277BD;
                color: white;
                border-radius: 10px;
                margin-right: 10px
            }
            QPushButton:hover{
                background-color: #499DD0;
                border-radius: 10px;
            }
        """)
        
        self.horizontalLayout_12.addWidget(self.setTimeThursday)
        
        self.verticalLayout_27.addLayout(self.horizontalLayout_12)
        self.verticalLayout_27.setStretch(0, 12)
        self.horizontalLayout_58.addLayout(self.verticalLayout_27)
        self.horizontalLayout_29.addWidget(self.thursday)
        
        self.friday = QtWidgets.QFrame(self.frame_2)
        self.friday.setStyleSheet("#friday{border: 2px  solid #757475;}")
        self.friday.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.friday.setFrameShadow(QtWidgets.QFrame.Raised)
        self.friday.setObjectName("friday")
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout(self.friday)
        self.horizontalLayout_59.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_59.setSpacing(0)
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setContentsMargins(-1, -1, -1, 8)
        self.verticalLayout_28.setSpacing(8)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_39 = QtWidgets.QLabel(self.friday)
        self.label_39.setMaximumSize(QtCore.QSize(16777215, 46))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_39.setFont(fontTitle)
        self.label_39.setStyleSheet("background:#3A3C41;color:white;")
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_28.addWidget(self.label_39)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(3, -1, 3, -1)
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")

        self.labelFriday = QtWidgets.QLabel(self.friday)
        self.labelFriday.setText('Set Time Table: ')
        self.labelFriday.setFont(font)
        self.labelFriday.setObjectName('Label Friday')
        self.labelFriday.setStyleSheet('color:white; padding-left: 10px ')

        self.horizontalLayout_13.addWidget(self.labelFriday)
        
        self.setTimeFriday = QtWidgets.QPushButton(self.friday)
        self.setTimeFriday.setFont(font)
        self.setTimeFriday.setObjectName('setTimeFriday')
        self.setTimeFriday.setText('Choose')
        self.setTimeFriday.setMinimumSize(QtCore.QSize(120,30))
        self.setTimeFriday.setMaximumSize(QtCore.QSize(120,30))
        self.setTimeFriday.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.setTimeFriday.setStyleSheet( """
            QPushButton{
                background-color: #4277BD;
                color: white;
                border-radius: 10px;
                margin-right: 10px
            }
            QPushButton:hover{
                background-color: #499DD0;
                border-radius: 10px;
            }
        """)
        
        self.horizontalLayout_13.addWidget(self.setTimeFriday)

        self.verticalLayout_28.addLayout(self.horizontalLayout_13)
        self.verticalLayout_28.setStretch(0, 12)
        self.horizontalLayout_59.addLayout(self.verticalLayout_28)
        self.horizontalLayout_29.addWidget(self.friday)
        
        self.saturday = QtWidgets.QFrame(self.frame_2)
        self.saturday.setStyleSheet("#saturday{border: 2px  solid #757475;}")
        self.saturday.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.saturday.setFrameShadow(QtWidgets.QFrame.Raised)
        self.saturday.setObjectName("saturday")
        self.horizontalLayout_60 = QtWidgets.QHBoxLayout(self.saturday)
        self.horizontalLayout_60.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_60.setSpacing(0)
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setContentsMargins(-1, -1, -1, 8)
        self.verticalLayout_31.setSpacing(8)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        
        self.label_42 = QtWidgets.QLabel(self.saturday)
        self.label_42.setMaximumSize(QtCore.QSize(16777215, 46))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_42.setFont(fontTitle)
        self.label_42.setStyleSheet("background:#3A3C41;color:white;")
        self.label_42.setText('星期日')
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_31.addWidget(self.label_42)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(3, -1, 3, -1)
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")

        self.labelSaturday = QtWidgets.QLabel(self.saturday)
        self.labelSaturday.setText('Set Time Table: ')
        self.labelSaturday.setFont(font)
        self.labelSaturday.setObjectName('Label Saturday')
        self.labelSaturday.setStyleSheet('color:white; padding-left: 10px ')

        self.horizontalLayout_14.addWidget(self.labelSaturday)
        
        self.setTimeSaturday = QtWidgets.QPushButton(self.saturday)
        self.setTimeSaturday.setFont(font)
        self.setTimeSaturday.setObjectName('setTimeTuesday')
        self.setTimeSaturday.setText('Choose')
        self.setTimeSaturday.setMinimumSize(QtCore.QSize(120,30))
        self.setTimeSaturday.setMaximumSize(QtCore.QSize(120,30))
        self.setTimeSaturday.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.setTimeSaturday.setStyleSheet( """
            QPushButton{
                background-color: #4277BD;
                color: white;
                border-radius: 10px;
                margin-right: 10px
            }
            QPushButton:hover{
                background-color: #499DD0;
                border-radius: 10px;
            }
        """)
        
        self.horizontalLayout_14.addWidget(self.setTimeSaturday)
    
        self.verticalLayout_31.addLayout(self.horizontalLayout_14)
        self.verticalLayout_31.setStretch(0, 12)
        self.horizontalLayout_60.addLayout(self.verticalLayout_31)
        self.horizontalLayout_29.addWidget(self.saturday)
        self.horizontalLayout_63.addLayout(self.horizontalLayout_29)
        self.verticalLayout_6.addLayout(self.horizontalLayout_63)
        
        self.horizontalLayout_64 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_64.setObjectName('horizontalLayout_64')
        self.horizontalLayout_64.setSpacing(0)
        
        ####### first frame ########
        self.sunday = QtWidgets.QFrame(self.frame_2)
        self.sunday.setStyleSheet("#sunday{border: 2px  solid #757475;}")
        self.sunday.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sunday.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sunday.setObjectName("sunday")
        
        self.horizontalLayout_591 = QtWidgets.QHBoxLayout(self.sunday)
        self.horizontalLayout_591.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_591.setSpacing(0)
        self.horizontalLayout_591.setObjectName("horizontalLayout_591")
        self.verticalLayout_281 = QtWidgets.QVBoxLayout()
        self.verticalLayout_281.setSpacing(0)
        self.verticalLayout_281.setObjectName("verticalLayout_281")
        self.label_391 = QtWidgets.QLabel(self.sunday)
        self.label_391.setMaximumSize(QtCore.QSize(16777215, 46))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_391.setFont(fontTitle)
        self.label_391.setStyleSheet("background:#3A3C41;color:white;")
        self.label_391.setAlignment(QtCore.Qt.AlignCenter)
        self.label_391.setFixedHeight(40)
        self.label_391.setText('星期日')
        self.label_391.setObjectName("label_391")
        self.verticalLayout_281.addWidget(self.label_391)

        self.horizontalLayout_131 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_131.setContentsMargins(3, -1, 3, -1)
        self.horizontalLayout_131.setSpacing(6)
        self.horizontalLayout_131.setObjectName("horizontalLayout_131")

        self.labelSunday = QtWidgets.QLabel(self.sunday)
        self.labelSunday.setText('Set Time Table: ')
        self.labelSunday.setFont(font)
        self.labelSunday.setObjectName('Label Sunday')
        self.labelSunday.setStyleSheet('color:white; padding-left: 10px ')

        self.horizontalLayout_131.addWidget(self.labelSunday)
        
        self.setTimeSunday = QtWidgets.QPushButton(self.sunday)
        self.setTimeSunday.setFont(font)
        self.setTimeSunday.setObjectName('setTimeSunday')
        self.setTimeSunday.setText('Choose')
        self.setTimeSunday.setMinimumSize(QtCore.QSize(120,30))
        self.setTimeSunday.setMaximumSize(QtCore.QSize(120,30))
        self.setTimeSunday.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.setTimeSunday.setStyleSheet( """
            QPushButton{
                background-color: #4277BD;
                color: white;
                border-radius: 10px;
                margin-right: 10px
            }
            QPushButton:hover{
                background-color: #499DD0;
                border-radius: 10px;
            }
        """)
        
        self.horizontalLayout_131.addWidget(self.setTimeSunday)

        self.verticalLayout_281.addLayout(self.horizontalLayout_131)

        self.horizontalLayout_591.addLayout(self.verticalLayout_281)

        ############################################

        self.GPIO = QtWidgets.QFrame(self.frame_2)
        self.GPIO.setStyleSheet("#GPIO{border: 2px  solid #757475;}")
        self.GPIO.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.GPIO.setFrameShadow(QtWidgets.QFrame.Raised)
        self.GPIO.setObjectName("GPIO")

        self.horizontalLayout_592 = QtWidgets.QHBoxLayout(self.GPIO)
        self.horizontalLayout_592.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_592.setSpacing(0)
        self.horizontalLayout_592.setObjectName("horizontalLayout_592")
        self.verticalLayout_282 = QtWidgets.QVBoxLayout()
        self.verticalLayout_282.setContentsMargins(-1, -1, -1, 8)
        self.verticalLayout_282.setSpacing(8)
        self.verticalLayout_282.setObjectName("verticalLayout_282")
        self.label_392 = QtWidgets.QLabel(self.sunday)
        self.label_392.setMaximumSize(QtCore.QSize(16777215, 46))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_392.setFont(fontTitle)
        self.label_392.setStyleSheet("background:#3A3C41;color:white;")
        self.label_392.setFixedHeight(40)
        self.label_392.setAlignment(QtCore.Qt.AlignCenter)
        self.label_392.setText('GPIO')
        self.label_392.setObjectName("label_392")
        self.verticalLayout_282.addItem(spacerItem)
        self.verticalLayout_282.addWidget(self.label_392)
        
        self.horizontalLayout_132 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_132.setContentsMargins(3, -1, 3, -1)
        self.horizontalLayout_132.setSpacing(6)
        self.horizontalLayout_132.setObjectName("horizontalLayout_132")

        self.labelGPIO1 = QtWidgets.QLabel()
        fontLabelGPIO = QtGui.QFont()
        fontLabelGPIO.setPointSize(20)
        self.labelGPIO1.setFont(fontLabelGPIO)
        self.labelGPIO1.setText('Camera 1: ')
        self.labelGPIO1.setStyleSheet('color:white;margin-left:10')
        self.horizontalLayout_132.addWidget(self.labelGPIO1)

        self.switchGPIO1= MySwitch()
        self.switchGPIO1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.switchGPIO1.setChecked(False)
        self.switchGPIO1.setObjectName('switchGPIO1')
        self.horizontalLayout_132.addWidget(self.switchGPIO1)
        
        self.verticalLayout_282.addLayout(self.horizontalLayout_132)

        self.horizontalGPIO2 = QtWidgets.QHBoxLayout()
        self.horizontalGPIO2.setContentsMargins(3,-1,3,-1)
        self.horizontalGPIO2.setSpacing(2)
        self.horizontalGPIO2.setObjectName('horizontalGPIO2')

        self.labelGPIO2 = QtWidgets.QLabel()
        self.labelGPIO2.setFont(fontLabelGPIO)
        self.labelGPIO2.setText('Camera 2: ')
        self.labelGPIO2.setStyleSheet('color:white;margin-left:10')
        
        self.horizontalGPIO2.addWidget(self.labelGPIO2)

        self.switchGPIO2= MySwitch()
        self.switchGPIO2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.switchGPIO2.setChecked(False)
        self.switchGPIO2.setObjectName('switchGPIO2')
        self.horizontalGPIO2.addWidget(self.switchGPIO2)

        self.verticalLayout_282.addLayout(self.horizontalGPIO2) 

        self.horizontalGPIO3 = QtWidgets.QHBoxLayout()
        self.horizontalGPIO3.setContentsMargins(3,-1,3,-1)
        self.horizontalGPIO3.setSpacing(2)
        self.horizontalGPIO3.setObjectName('horizontalGPIO3')

        self.labelGPIO3 = QtWidgets.QLabel()
        self.labelGPIO3.setFont(fontLabelGPIO)
        self.labelGPIO3.setText('Camera 3: ')
        self.labelGPIO3.setStyleSheet('color:white;margin-left:10')
        self.horizontalGPIO3.addWidget(self.labelGPIO3)

        self.switchGPIO3= MySwitch()
        self.switchGPIO3.setChecked(False)
        self.switchGPIO3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.switchGPIO3.setObjectName('switchGPIO3')
        self.horizontalGPIO3.addWidget(self.switchGPIO3)

        self.verticalLayout_282.addLayout(self.horizontalGPIO3)

        self.horizontalGPIO4 = QtWidgets.QHBoxLayout()
        self.horizontalGPIO4.setContentsMargins(3,-1,3,-1)
        self.horizontalGPIO4.setSpacing(2)
        self.horizontalGPIO4.setObjectName('horizontalGPIO4')

        self.labelGPIO4 = QtWidgets.QLabel()
        self.labelGPIO4.setFont(fontLabelGPIO)
        self.labelGPIO4.setText('Camera 4: ')
        self.labelGPIO4.setStyleSheet('color:white;margin-left:10')
        self.horizontalGPIO4.addWidget(self.labelGPIO4)

        self.switchGPIO4= MySwitch()
        self.switchGPIO4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.switchGPIO4.setChecked(False)
        self.switchGPIO4.setObjectName('switchGPIO4')
        self.horizontalGPIO4.addWidget(self.switchGPIO4)

        self.verticalLayout_282.addLayout(self.horizontalGPIO4)  

        self.horizontalLayout_592.addLayout(self.verticalLayout_282)
        ############################################################

        self.settings = QtWidgets.QFrame(self.frame_2)
        self.settings.setStyleSheet("#settings{border: 2px  solid #757475;}")
        self.settings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settings.setObjectName("settings")

        self.horizontalLayout_593 = QtWidgets.QHBoxLayout(self.settings)
        self.horizontalLayout_593.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_593.setSpacing(0)
        self.horizontalLayout_593.setObjectName("horizontalLayout_592")
        self.verticalLayout_283 = QtWidgets.QVBoxLayout()
        self.verticalLayout_283.setContentsMargins(-1, -1, -1, 8)
        self.verticalLayout_283.setSpacing(8)
        self.verticalLayout_283.setObjectName("verticalLayout_283")
        self.label_393 = QtWidgets.QLabel(self.settings)
        self.label_393.setMaximumSize(QtCore.QSize(16777215, 46))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_393.setFont(fontTitle)
        self.label_393.setStyleSheet("background:#3A3C41;color:white;")
        self.label_393.setFixedHeight(40)
        self.label_393.setAlignment(QtCore.Qt.AlignCenter)
        self.label_393.setText('Settings')
        self.label_393.setObjectName("label_392")
        self.verticalLayout_283.addItem(spacerItem)
        self.verticalLayout_283.addWidget(self.label_393)

        self.horizontalreset = QtWidgets.QHBoxLayout()
        self.horizontalreset.setSpacing(0)
        self.horizontalreset.setObjectName('horizontalReset')

        self.label_16 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color:white;")
        self.label_16.setObjectName("label_16")
        self.horizontalreset.addItem(spacerItem)
        self.horizontalreset.addWidget(self.label_16)
        self.horizontalreset.addItem(spacerItem)

        self.counterrestart = QtWidgets.QTimeEdit(self.frame_2)
        self.counterrestart.setFont(font)
        self.counterrestart.setStyleSheet("color:white;")
        self.counterrestart.setObjectName("counterrestart")
        self.horizontalreset.addWidget(self.counterrestart)
        self.horizontalreset.addItem(spacerItem)

        self.verticalLayout_283.addLayout(self.horizontalreset)

        self.falldelay = QtWidgets.QHBoxLayout()
        self.falldelay.setSpacing(0)
        self.falldelay.setObjectName('falldelay')

        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color:white")
        self.label_17.setObjectName('label_17')
        self.falldelay.addItem(spacerItem)
        self.falldelay.addWidget(self.label_17)
        self.falldelay.addItem(spacerItem)

        self.delay = QtWidgets.QSpinBox(self.frame_2)
        self.delay.setFont(font)
        self.delay.setStyleSheet('color:white')
        self.delay.setProperty("value",1)
        self.delay.setObjectName('delay')
        self.falldelay.addWidget(self.delay)

        self.label_44 = QtWidgets.QLabel(self.frame_2)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet('color:white')
        self.label_44.setObjectName('label_44')

        self.falldelay.addWidget(self.label_44)
        self.falldelay.addItem(spacerItem)

        self.verticalLayout_283.addLayout(self.falldelay)

        self.horizontalLayout_593.addLayout(self.verticalLayout_283)

        self.horizontalLayout_64.addWidget(self.sunday)
        self.horizontalLayout_64.addWidget(self.GPIO)
        self.horizontalLayout_64.addWidget(self.settings)

        self.horizontalLayout_64.setStretch(0,5)
        self.horizontalLayout_64.setStretch(1,5)
        self.horizontalLayout_64.setStretch(2,5)

        self.verticalLayout_6.addLayout(self.horizontalLayout_64)
        
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)

        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 7)
        self.horizontalLayout_7.setStretch(2, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7) #2
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem13) #3
        

        spacerItem63 = QtWidgets.QSpacerItem(1058, 59, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem63) #4
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem64 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem64)
        self.back = QtWidgets.QPushButton(self.frame_2)
        self.back.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        self.back.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.back.setFont(font)
        self.back.setStyleSheet("QPushButton{\n"
"background:#323232;color:white;border: 2px  solid #757475;"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:lightgray;\n"
"    color:black;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:gray;\n"
"    color:white"
"}\n"
"")
        self.back.setObjectName("back")
        self.horizontalLayout_18.addWidget(self.back)
        spacerItem66 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem66)
        self.start = QtWidgets.QPushButton(self.frame_2)
        self.start.setCursor(QCursor(QtCore.Qt.PointingHandCursor))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start.sizePolicy().hasHeightForWidth())
        self.start.setSizePolicy(sizePolicy)
        self.start.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.start.setFont(font)
        self.start.setStyleSheet("QPushButton{\n"
"background:#069CFF;color:black;border: 2px  solid #757475;;"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:lightblue;\n"
"    color:black;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:blue;\n"
"    color:white"
"}\n"
"")
        self.start.setObjectName("start")
        self.horizontalLayout_18.addWidget(self.start)
        spacerItem67 = QtWidgets.QSpacerItem(180, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem67)
        self.horizontalLayout_18.setStretch(0, 34)
        self.horizontalLayout_18.setStretch(1, 2)
        self.horizontalLayout_18.setStretch(3, 2)
        self.horizontalLayout_18.setStretch(5, 2)
        self.horizontalLayout_18.setStretch(6, 4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18) #5
        spacerItem68 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem68) #6
        self.verticalLayout_5.setStretch(0, 3)
        self.verticalLayout_5.setStretch(1, 24)
        self.verticalLayout_5.setStretch(2, 1)
        self.verticalLayout_5.setStretch(3, 4)
        self.verticalLayout_5.setStretch(4, 1)
        self.verticalLayout_5.setStretch(5, 1)
        self.horizontalLayout.addWidget(self.frame_2)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 20)
        self.horizontalLayout_11.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 80)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4.setStretch(0, 80)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_6.setIcon(QtGui.QIcon("images/home_white.png"))
        self.pushButton_6.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_8.setIcon(QtGui.QIcon("images/video.png"))
        self.pushButton_8.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_7.setIcon(QtGui.QIcon("images/settings_white.png"))
        self.pushButton_7.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_search.setIcon(QtGui.QIcon("images/search_pls.png"))
        self.pushButton_search.setIconSize(QtCore.QSize(85,85))
        
        self.label_23.setText(_translate("MainWindow", "功能設定"))
        self.pushButton_2.setText(_translate("MainWindow", "Camera Settings"))
        self.pushButton_0.setText(_translate("MainWindow", "Device Settings"))
        self.pushButton_3.setText(_translate("MainWindow", "功能設定"))
        self.pushButton_4.setText(_translate("MainWindow", "AI Settings"))
        self.pushButton_5.setText(_translate("MainWindow", "Log"))
        self.label_26.setText(_translate("MainWindow", "星期一"))
        self.label_36.setText(_translate("MainWindow", "星期二"))
        self.label_37.setText(_translate("MainWindow", "星期三"))
        self.label_38.setText(_translate("MainWindow", "星期四"))
        self.label_39.setText(_translate("MainWindow", "星期五"))
        
        self.label_16.setText(_translate("MainWindow", "Reset Time:   "))
        self.counterrestart.setDisplayFormat(_translate("MainWindow", "HH:mm"))
        self.label_17.setText(_translate("MainWindow", "Detection Delay: "))
        self.label_44.setText(_translate("MainWindow", "秒"))
        self.back.setText(_translate("MainWindow", "還原"))
        self.start.setText(_translate("MainWindow", "確定"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
