# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newsettingmain.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from mySwitch import MySwitch

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1120)
        MainWindow.setStyleSheet("background:black;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("background-image : url(background.png);")
        self.centralwidget.setObjectName("centralwidget")
        
        #############################################################################################################
        #############################################################################################################
        
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        
        self.label_10 = QtWidgets.QLabel(self.centralwidget) #logo
        self.label_10.setMaximumSize(QtCore.QSize(540, 95))
        self.label_10.setStyleSheet("background:blue")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("logoo.png"))
        self.label_10.setScaledContents(False)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10) #horizontal 0
        
        self.horizontalLayout_logo = QtWidgets.QHBoxLayout()
        self.horizontalLayout_logo.setSpacing(0)
        self.horizontalLayout_logo.setObjectName("HorizontalLayout_logo")
        
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget) #go back to menu
        self.pushButton_6.setMinimumSize(QtCore.QSize(80,80))
        self.pushButton_6.setMaximumSize(QtCore.QSize(80,80))
        self.pushButton_6.setStyleSheet("""
                                        QPushButton{
                                                background-color: black;
                                                color:white;
                                                border-radius:10px;
                                        }
                                        QPushButton:hover{
                                                background-color: #00BDFE;
                                        }
                                """)
        self.pushButton_6.setDefault(True)
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout_logo.addWidget(self.pushButton_6)
        
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_logo.addItem(spacerItem) 
        
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget) 
        self.pushButton_7.setMinimumSize(QtCore.QSize(80,80))
        self.pushButton_7.setMaximumSize(QtCore.QSize(80,80))
        self.pushButton_7.setStyleSheet("""
                                        QPushButton{
                                                background-color: #00BDFE;
                                                color:white;
                                                border-radius:10px;
                                        }
                                        QPushButton:hover{
                                                background-color: #00BDFE;
                                        }
                                """)
        self.pushButton_7.setDefault(True)
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout_logo.addWidget(self.pushButton_7) 
        
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_logo.addItem(spacerItem1) 

        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget) #gotosettings
        self.pushButton_8.setMinimumSize(QtCore.QSize(80,80))
        self.pushButton_8.setMaximumSize(QtCore.QSize(80,80))
        self.pushButton_8.setStyleSheet("""
                                        QPushButton{
                                                background-color: black;
                                                color:white;
                                                border-radius:10px;
                                        }
                                        QPushButton:hover{
                                                background-color: #00BDFE;
                                        }
                                """)
        self.pushButton_8.setDefault(True)
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout_logo.addWidget(self.pushButton_8) 
        
        self.horizontalLayout_logo.addItem(spacerItem)
        
        self.pushButton_search = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_search.setMinimumSize(QtCore.QSize(80,80))
        self.pushButton_search.setMaximumSize(QtCore.QSize(80,80))
        self.pushButton_search.setStyleSheet("""
                                        QPushButton{
                                                background-color: black;
                                                color:white;
                                                border-radius:10px;
                                        }
                                        QPushButton:hover{
                                                background-color: #00BDFE;
                                        }
                                """)
        self.pushButton_search.setDefault(True)
        self.pushButton_search.setFlat(True)
        self.pushButton_search.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_search.setObjectName("PushButton_search")
        self.horizontalLayout_logo.addWidget(self.pushButton_search)
        
        self.horizontalLayout_logo.addItem(spacerItem)
        
        self.horizontalLayout_logo.setStretch(0,10)
        self.horizontalLayout_logo.setStretch(1,1)
        self.horizontalLayout_logo.setStretch(2,9)
        self.horizontalLayout_logo.setStretch(3,1)
        self.horizontalLayout_logo.setStretch(4,9)
        self.horizontalLayout_logo.setStretch(5,1)
        self.horizontalLayout_logo.setStretch(6,9)
        self.horizontalLayout_logo.setStretch(8,10)
        
        self.horizontalLayout_5.addLayout(self.horizontalLayout_logo) #horizontal -2
        
        
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3) #horizontal -3
        
        self.label_23 = QtWidgets.QLabel(self.centralwidget) #tanda window
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK TC")
        font.setPointSize(20)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color:#707070;")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_5.addWidget(self.label_23) #horizontal -4
        
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4) #horizontal - 5
        
        self.ppe = QtWidgets.QPushButton(self.centralwidget)#logo
        self.ppe.setMaximumSize(QtCore.QSize(60, 60))
        self.ppe.setAutoFillBackground(False)
        self.ppe.setStyleSheet("border-radius: 15px;")
        self.ppe.setText("")
        self.ppe.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Group 104.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ppe.setIcon(icon)
        self.ppe.setIconSize(QtCore.QSize(60, 60))
        self.ppe.setObjectName("ppe")
        self.horizontalLayout_5.addWidget(self.ppe) #horizontal - 6
        
        
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5) #horizontal - 7
        
        self.horizontalLayout_5.setStretch(0, 3)
        self.horizontalLayout_5.setStretch(1, 80)
        self.horizontalLayout_5.setStretch(2, 10)
        self.horizontalLayout_5.setStretch(3, 1)
        self.horizontalLayout_5.setStretch(4, 1)
        self.horizontalLayout_5.setStretch(5, 1)
        self.horizontalLayout_5.setStretch(6, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        
        #############################################################################################################
        #############################################################################################################
        #settings kiri
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background:#121E28;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        
        
        self.pushButton_2 = QtWidgets.QPushButton(self.frame) #settings 1 and 2
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color:white;")
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setObjectName("pushButton_2") #gong neng
        self.verticalLayout.addWidget(self.pushButton_2)
        
        self.pushButton_0 = QtWidgets.QPushButton(self.frame) #settings 1 and 2
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setStyleSheet("background:#3A3C41;color:white;")
        self.pushButton_0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_0.setObjectName("pushButton_0") #gong neng
        self.verticalLayout.addWidget(self.pushButton_0)
        
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("color:white;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.verticalLayout.addWidget(self.pushButton_3)
        
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)#belum ke isi
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setAutoFillBackground(False)
        self.pushButton_4.setStyleSheet("color:white;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.verticalLayout.addWidget(self.pushButton_4)

        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setAutoFillBackground(False)
        self.pushButton_5.setStyleSheet('color: white')
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.verticalLayout.addWidget(self.pushButton_5)

        self.pushButtonReset = QtWidgets.QPushButton(self.frame)
        self.pushButtonReset.setText('Factory Reset')
        self.pushButtonReset.setFont(font)
        self.pushButtonReset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonReset.setAutoFillBackground(False)
        self.pushButtonReset.setStyleSheet('color: white')
        self.verticalLayout.addWidget(self.pushButtonReset, alignment = QtCore.Qt.AlignBottom)
        
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        
        self.verticalLayout_4.addLayout(self.verticalLayout)
        
        self.horizontalLayout.addWidget(self.frame)
        
        #############################################################################################################
        #############################################################################################################
        #main settings
        
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background:black")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        
        
        #############################################################################################################
        #############################################################################################################

        self.tabs = QtWidgets.QTabWidget()
        self.tabs.setStyleSheet("""
            QTabWidget::tab-bar {
                                border: 1px solid gray;
                                }
                                
                            QTabBar::tab {
                                background: #4277BD;
                                color: white;
                                padding: 10px;
                                width : 200px;
                                height:30px;
                                border-top-left-radius: 5;
                                border-top-right-radius: 5;
                                font-size: 20px;
                            }

                            QTabBar::tab:selected {
                                background: black;
                                margin-bottom: -1px; 
                            }
                            QTabWidget::pane { 
                                border: none;
                                top:-1px; 
                            }
        """)


        self.tab1 = QtWidgets.QWidget()
        self.tab2 = QtWidgets.QWidget()
        self.tab3 = QtWidgets.QWidget()
        
        self.tabs.addTab(self.tab1, "Box's Settings")
        self.tabs.addTab(self.tab2, "Software Updates")
        self.tabs.addTab(self.tab3, "File Export")

        self.tab1.layout = QtWidgets.QVBoxLayout()
        self.tab1.layout.setSpacing(0)

        self.tab1.layout.addItem(spacerItem)

        self.frameTime = QtWidgets.QFrame()
        self.frameTime.Shape(QtWidgets.QFrame.Box)
        self.frameTime.setMaximumHeight(400)
        self.frameTime.setFrameStyle(QtWidgets.QFrame.Panel | QtWidgets.QFrame.Sunken)
        self.frameTime.setObjectName("frameTime")
        self.frameTime.setStyleSheet("""#frameTime{border:3px solid blue; padding 10;}""")

        self.verticalTimeLayout = QtWidgets.QVBoxLayout(self.frameTime)
        self.verticalTimeLayout.setSpacing(0)

        self.settingsTime = QtWidgets.QLabel()
        self.settingsTime.setText("Time Settings")
        self.settingsTime.setStyleSheet("color:white")
        self.settingsTime.setFont(font)
        self.verticalTimeLayout.addWidget(self.settingsTime)#0
        self.verticalTimeLayout.addItem(spacerItem)#1

        self.HorizontalNTP = QtWidgets.QHBoxLayout()
        self.HorizontalNTP.setSpacing(0)

        self.NTPServer = QtWidgets.QLabel()
        self.NTPServer.setText("NTP Server")
        self.NTPServer.setStyleSheet("color:white")
        self.NTPServer.setFont(font)
        self.HorizontalNTP.addItem(spacerItem)
        self.HorizontalNTP.addWidget(self.NTPServer)

        self.NTPSwitch = MySwitch()
        self.NTPSwitch.setChecked(True)
        self.NTPSwitch.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.HorizontalNTP.addItem(spacerItem)
        self.HorizontalNTP.addWidget(self.NTPSwitch)
        self.HorizontalNTP.addItem(spacerItem)

        self.HorizontalNTP.setStretch(0,1)
        self.HorizontalNTP.setStretch(1,1)
        self.HorizontalNTP.setStretch(2,1)
        self.HorizontalNTP.setStretch(3,5)
        self.HorizontalNTP.setStretch(4,24)

        self.verticalTimeLayout.addLayout(self.HorizontalNTP)#2
        self.verticalTimeLayout.addItem(spacerItem)#3

        self.HorizontalTimeZone = QtWidgets.QHBoxLayout()
        self.HorizontalTimeZone.setSpacing(0)
        self.HorizontalTimeZone.addItem(spacerItem)

        self.TimeLabel = QtWidgets.QLabel()
        self.TimeLabel.setText('')
        self.TimeLabel.setFont(font)
        self.TimeLabel.setStyleSheet('color:white')
        self.HorizontalTimeZone.addWidget(self.TimeLabel)
        self.HorizontalTimeZone.addItem(spacerItem)

        self.TimeInput = QtWidgets.QLineEdit()
        self.TimeInput.setFont(font)
        self.TimeInput.setStyleSheet('background:#EEF4F9')
        self.TimeInput.setText("")
        self.HorizontalTimeZone.addWidget(self.TimeInput)
        self.HorizontalTimeZone.addItem(spacerItem)

        self.TimeButton = QtWidgets.QPushButton()
        self.TimeButton.setFont(font)
        self.TimeButton.setText("")
        self.TimeButton.setStyleSheet("""
            QPushButton{
                background-color: #4277BD;
                color: white;
                border-radius: 10px;
            }
            QPushButton:hover{
                background-color: #499DD0;
                border-radius: 10px;
            }
        """)
        self.TimeButton.setMaximumSize(QtCore.QSize(80,30))
        self.TimeButton.setMinimumSize(QtCore.QSize(80,30))
        self.TimeButton.setFlat(True)
        self.TimeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.HorizontalTimeZone.addWidget(self.TimeButton)
        self.HorizontalTimeZone.addItem(spacerItem)

        self.HorizontalTimeZone.setStretch(0,2)
        self.HorizontalTimeZone.setStretch(1,5)
        self.HorizontalTimeZone.setStretch(2,1)
        self.HorizontalTimeZone.setStretch(3,8)
        self.HorizontalTimeZone.setStretch(4,2)
        self.HorizontalTimeZone.setStretch(5,10)
        self.HorizontalTimeZone.setStretch(6,43)

        self.verticalTimeLayout.addLayout(self.HorizontalTimeZone)#4

        self.HorizontalManual = QtWidgets.QHBoxLayout()
        self.HorizontalManual.setSpacing(0)

        self.ManualLabel = QtWidgets.QLabel()
        self.ManualLabel.setText("Time Manual Input")
        self.ManualLabel.setStyleSheet('color:white')
        self.ManualLabel.setFont(font)
        self.HorizontalManual.addItem(spacerItem)
        self.HorizontalManual.addWidget(self.ManualLabel)
        self.HorizontalManual.addItem(spacerItem)

        self.ManualSwitch = MySwitch()
        self.ManualSwitch.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ManualSwitch.setChecked(False)
        self.HorizontalManual.addWidget(self.ManualSwitch)
        self.HorizontalManual.addItem(spacerItem)

        self.HorizontalManual.setStretch(0,2)
        self.HorizontalManual.setStretch(1,2)
        self.HorizontalManual.setStretch(2,1)
        self.HorizontalManual.setStretch(3,5)
        self.HorizontalManual.setStretch(4,48)

        self.verticalTimeLayout.addItem(spacerItem)#5
        self.verticalTimeLayout.addLayout(self.HorizontalManual)#6
        self.verticalTimeLayout.addItem(spacerItem)#7

        self.horizontalzijidate = QtWidgets.QHBoxLayout()
        self.horizontalzijidate.setSpacing(0)
        self.horizontalzijidate.addItem(spacerItem)

        self.zidateLabel = QtWidgets.QLabel()
        self.zidateLabel.setText('Date')
        self.zidateLabel.setFont(font)
        self.zidateLabel.setStyleSheet('color:white')
        self.horizontalzijidate.addWidget(self.zidateLabel)
        self.horizontalzijidate.addItem(spacerItem)

        self.zidateInput = QtWidgets.QLineEdit()
        self.zidateInput.setStyleSheet('background:#EEF4F9')
        self.zidateInput.setPlaceholderText('YYYY-MM-DD')
        self.zidateInput.setText('')
        self.zidateInput.setFont(font)
        self.horizontalzijidate.addWidget(self.zidateInput)
        self.horizontalzijidate.addItem(spacerItem)

        self.horizontalzijidate.setStretch(0,3)
        self.horizontalzijidate.setStretch(1,6)
        self.horizontalzijidate.setStretch(2,4)
        self.horizontalzijidate.setStretch(3,13)
        self.horizontalzijidate.setStretch(4,80)

        self.verticalTimeLayout.addLayout(self.horizontalzijidate)
        self.verticalTimeLayout.addItem(spacerItem)

        self.horizontalzijiTime = QtWidgets.QHBoxLayout()
        self.horizontalzijiTime.setSpacing(0)
 
        self.zijiLabel = QtWidgets.QLabel()
        self.zijiLabel.setText('Time')
        self.zijiLabel.setFont(font)
        self.zijiLabel.setStyleSheet("color:white")
        self.horizontalzijiTime.addItem(spacerItem)
        self.horizontalzijiTime.addWidget(self.zijiLabel)
        self.horizontalzijiTime.addItem(spacerItem)

        self.zijiInput = QtWidgets.QLineEdit()
        self.zijiInput.setStyleSheet('background:#EEF4F9')
        self.zijiInput.setText('')
        self.zijiInput.setPlaceholderText('HH:MM:SS')
        self.zijiInput.setFont(font)
        self.horizontalzijiTime.addWidget(self.zijiInput)
        self.horizontalzijiTime.addItem(spacerItem)

        self.zijiButton = QtWidgets.QPushButton()
        self.zijiButton.setStyleSheet("""
            QPushButton{
                background-color: #4277BD;
                color: white;
                border-radius: 10px;
            }
            QPushButton:hover{
                background-color: #499DD0;
                border-radius: 10px;
            }
        """)
        self.zijiButton.setText('Set')
        self.zijiButton.setFont(font)
        self.zijiButton.setFlat(True)
        self.zijiButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.zijiButton.setMinimumSize(QtCore.QSize(80,30))
        self.zijiButton.setMaximumSize(QtCore.QSize(80,30))
        self.horizontalzijiTime.addWidget(self.zijiButton)
        self.horizontalzijiTime.addItem(spacerItem)

        self.horizontalzijiTime.setStretch(0,2)
        self.horizontalzijiTime.setStretch(1,5)
        self.horizontalzijiTime.setStretch(2,1)
        self.horizontalzijiTime.setStretch(3,8)
        self.horizontalzijiTime.setStretch(4,2)
        self.horizontalzijiTime.setStretch(5,10)
        self.horizontalzijiTime.setStretch(6,43)

        self.verticalTimeLayout.addLayout(self.horizontalzijiTime)#8
        self.verticalTimeLayout.addItem(spacerItem)#9

        self.verticalTimeLayout.setStretch(0,1)
        self.verticalTimeLayout.setStretch(1,1)
        self.verticalTimeLayout.setStretch(2,2)
        self.verticalTimeLayout.setStretch(3,1)
        self.verticalTimeLayout.setStretch(4,1)
        self.verticalTimeLayout.setStretch(5,3)
        self.verticalTimeLayout.setStretch(6,1)
        self.verticalTimeLayout.setStretch(7,1)
        self.verticalTimeLayout.setStretch(8,1)
        self.verticalTimeLayout.setStretch(9,1)
        self.verticalTimeLayout.setStretch(10,1)
        self.verticalTimeLayout.setStretch(11,1)

        self.tab1.layout.addWidget(self.frameTime)

        self.frameIP = QtWidgets.QFrame()
        self.frameIP.Shape(QtWidgets.QFrame.Box)
        self.frameIP.setMaximumHeight(200)
        self.frameIP.setFrameStyle(QtWidgets.QFrame.Panel | QtWidgets.QFrame.Sunken)
        self.frameIP.setObjectName("frameIP")
        self.frameIP.setStyleSheet("#frameIP{border: 3px solid blue; padding: 10px}")

        self.VerticalIP = QtWidgets.QVBoxLayout(self.frameIP)
        self.VerticalIP.setSpacing(0)

        self.IPSettings = QtWidgets.QLabel()
        self.IPSettings.setText('IP Settings')
        self.IPSettings.setFont(font)
        self.IPSettings.setStyleSheet("color:white")
        self.VerticalIP.addItem(spacerItem)
        self.VerticalIP.addWidget(self.IPSettings)
        self.VerticalIP.addItem(spacerItem)

        self.horizontalIP =QtWidgets.QHBoxLayout()
        self.horizontalIP.setSpacing(0)
        self.horizontalIP.addItem(spacerItem)

        self.IpLabel = QtWidgets.QLabel()
        self.IpLabel.setText('Set Ip Address')
        self.IpLabel.setFont(font)
        self.IpLabel.setStyleSheet('color:white')
        self.horizontalIP.addWidget(self.IpLabel)
        self.horizontalIP.addItem(spacerItem)

        self.IpInput = QtWidgets.QLineEdit()
        self.IpInput.setStyleSheet('background:#EEF4F9')
        self.IpInput.setText('')
        self.IpInput.setFont(font)
        self.horizontalIP.addWidget(self.IpInput)
        self.horizontalIP.addItem(spacerItem)

        self.IPButton = QtWidgets.QPushButton()
        self.IPButton.setText('Set')
        self.IPButton.setStyleSheet("""
            QPushButton{
                background-color: #4277BD;
                color: white;
                border-radius: 10px;
            }
            QPushButton:hover{
                background-color: #499DD0;
                border-radius: 10px;
            }
        """)
        self.IPButton.setFlat(True)
        self.IPButton.setFont(font)
        self.IPButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.IPButton.setMinimumSize(QtCore.QSize(80,30))
        self.IPButton.setMaximumSize(QtCore.QSize(80,30))
        self.horizontalIP.addWidget(self.IPButton)
        self.horizontalIP.addItem(spacerItem)

        self.horizontalIP.setStretch(0,2)
        self.horizontalIP.setStretch(1,5)
        self.horizontalIP.setStretch(2,1)
        self.horizontalIP.setStretch(3,8)
        self.horizontalIP.setStretch(4,2)
        self.horizontalIP.setStretch(5,10)
        self.horizontalIP.setStretch(6,53)

        self.VerticalIP.addLayout(self.horizontalIP)
        self.VerticalIP.addItem(spacerItem)

        self.tab1.layout.addItem(spacerItem)
        self.tab1.layout.addWidget(self.frameIP)
        self.tab1.layout.addItem(spacerItem)

        self.tab1.layout.setStretch(0,1)
        self.tab1.layout.setStretch(1,5)
        self.tab1.layout.setStretch(2,1)
        self.tab1.layout.setStretch(3,5)
        self.tab1.layout.setStretch(4,20)

        self.tab1.setLayout(self.tab1.layout)

        self.tab2.layout = QtWidgets.QVBoxLayout()
        self.tab2.layout.setSpacing(0)
        self.tab2.setLayout(self.tab2.layout)

        self.UpdateLabel = QtWidgets.QLabel()
        self.UpdateLabel.setText('Software Settings')
        self.UpdateLabel.setFont(font)
        self.UpdateLabel.setStyleSheet('color:white; margin-left:20')
        self.tab2.layout.addItem(spacerItem) #0
        self.tab2.layout.addWidget(self.UpdateLabel) #1
        self.tab2.layout.addItem(spacerItem) #2

        self.HorizontalUpdate = QtWidgets.QHBoxLayout()
        self.HorizontalUpdate.setSpacing(0)

        fontLog = QtGui.QFont()
        fontLog.setFamily('Noto Sans CJK TC')
        fontLog.setPointSize(10)
        
        self.UpdateLabel = QtWidgets.QLabel()
        self.UpdateLabel.setFont(font)
        self.UpdateLabel.setStyleSheet('color: white')
        self.UpdateLabel.setText('Update Software')
        self.HorizontalUpdate.addItem(spacerItem)
        self.HorizontalUpdate.addWidget(self.UpdateLabel)

        self.UpdateButton = QtWidgets.QPushButton()
        self.UpdateButton.setText('Update')
        self.UpdateButton.setFont(font)
        self.UpdateButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.UpdateButton.setStyleSheet("""
            QPushButton{
                background-color: #4277BD;
                color: white;
                border-radius: 10px;
            }
            QPushButton:hover{
                background-color: #499DD0;
                border-radius:10px;
            }
        """)      
        self.UpdateButton.setMaximumSize(QtCore.QSize(80,30))
        self.UpdateButton.setMinimumSize(QtCore.QSize(80,30))

        self.HorizontalUpdate.addItem(spacerItem)
        self.HorizontalUpdate.addWidget(self.UpdateButton)
        self.HorizontalUpdate.addItem(spacerItem)

        self.HorizontalUpdate.setStretch(0,2)
        self.HorizontalUpdate.setStretch(1,5)
        self.HorizontalUpdate.setStretch(2,1)
        self.HorizontalUpdate.setStretch(3,5)
        self.HorizontalUpdate.setStretch(4,40) 

        self.versionLabel = QtWidgets.QLabel()
        self.versionLabel.setFont(fontLog)
        self.versionLabel.setStyleSheet('color:#7e7e7e; margin-left:28')
        self.versionLabel.setText('Version: 0.0')

        self.tab2.layout.addLayout(self.HorizontalUpdate) #3
        self.tab2.layout.addWidget(self.versionLabel)
        self.tab2.layout.addItem(spacerItem)#4


        self.sycnLabel = QtWidgets.QLabel()
        self.sycnLabel.setText('Server Sync Settings')
        self.sycnLabel.setFont(font)
        self.sycnLabel.setStyleSheet('color:white; margin-left:20')
        self.tab2.layout.addWidget(self.sycnLabel) #5 
        self.tab2.layout.addItem(spacerItem) #6

        self.horizontalLayout_time = QtWidgets.QHBoxLayout()
        self.horizontalLayout_time.setObjectName("horizontalLayout_time")
        self.horizontalLayout_time.addItem(spacerItem) #0
        
        self.label_time = QtWidgets.QLabel()
        self.label_time.setFont(font)
        self.label_time.setStyleSheet("color:white")
        self.label_time.setObjectName('label_time')
        self.horizontalLayout_time.addWidget(self.label_time) #1
        self.horizontalLayout_time.addItem(spacerItem) #2
        
        self.spin_time = QtWidgets.QSpinBox()
        font = QtGui.QFont()
        font.setPointSize(16)
        self.spin_time.setFont(font)
        self.spin_time.setStyleSheet("background: white")
        self.spin_time.setObjectName("spin_time")
        self.horizontalLayout_time.addWidget(self.spin_time) #3
        self.horizontalLayout_time.addItem(spacerItem) #4
        
        self.satuan = QtWidgets.QLabel()
        self.satuan.setFont(font)
        self.satuan.setStyleSheet('color:white')
        self.satuan.setObjectName('satuan')
        self.horizontalLayout_time.addWidget(self.satuan) #5
        self.horizontalLayout_time.addItem(spacerItem) #6
        
        self.horizontalLayout_time.setStretch(0,3)
        self.horizontalLayout_time.setStretch(1,5)
        self.horizontalLayout_time.setStretch(2,1)
        self.horizontalLayout_time.setStretch(3,5)
        self.horizontalLayout_time.setStretch(4,1)
        self.horizontalLayout_time.setStretch(5,5)
        self.horizontalLayout_time.setStretch(6,55)
                
        self.tab2.layout.addLayout(self.horizontalLayout_time)#7
        self.tab2.layout.addItem(spacerItem)#8
        
        ################################################################
        
        self.horizontalLayout_async = QtWidgets.QHBoxLayout()
        self.horizontalLayout_async.setSpacing(0)
        self.horizontalLayout_async.setObjectName("horizontalLayout_async")
        self.horizontalLayout_async.addItem(spacerItem)
        
        self.asyncLabel = QtWidgets.QLabel()
        self.asyncLabel.setFont(font)
        self.asyncLabel.setStyleSheet("color:white")
        self.asyncLabel.setObjectName("async Label")
        
        self.horizontalLayout_async.addWidget(self.asyncLabel)
        self.horizontalLayout_async.addItem(spacerItem)
        
        self.asyncSwitch = MySwitch()
        self.asyncSwitch.setChecked(True)
        self.asyncSwitch.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.asyncSwitch.setObjectName("asyncSwitch")
        self.horizontalLayout_async.addWidget(self.asyncSwitch)
        self.horizontalLayout_async.addItem(spacerItem)
        
        self.horizontalLayout_async.setStretch(0,3)
        self.horizontalLayout_async.setStretch(1,5)
        self.horizontalLayout_async.setStretch(2,1)
        self.horizontalLayout_async.setStretch(3,5)
        self.horizontalLayout_async.setStretch(4,60)
        
        self.tab2.layout.addLayout(self.horizontalLayout_async)#9

        self.lastSync = QtWidgets.QHBoxLayout()
        self.lastSync.setSpacing(0)

        self.lastSyncLabel = QtWidgets.QLabel()
        self.lastSyncLabel.setFont(fontLog)
        self.lastSyncLabel.setStyleSheet('color:#7e7e7e;margin-left: 28')
        self.lastSyncLabel.setText('Last Sync: ')
        self.lastSync.addWidget(self.lastSyncLabel)

        self.syncTime = QtWidgets.QLabel()
        self.syncTime.setFont(fontLog)
        self.syncTime.setStyleSheet('color:#7e7e7e;margin-left:28')
        self.syncTime.setText('10:12')
        self.lastSync.addWidget(self.syncTime)

        self.lastSync.addItem(spacerItem)

        self.lastSync.setStretch(0,1)
        self.lastSync.setStretch(1,1)
        self.lastSync.setStretch(2,20)

        self.tab2.layout.addLayout(self.lastSync)

        self.connect = QtWidgets.QLabel()
        self.connect.setText('Connected with  192.168.0.107')
        self.connect.setStyleSheet('color:#7e7e7e;margin-left:28')
        self.connect.setFont(fontLog)

        self.tab2.layout.addWidget(self.connect)
        self.tab2.layout.addItem(spacerItem)#10

        self.tab2.layout.setStretch(0,1)
        self.tab2.layout.setStretch(1,1)
        self.tab2.layout.setStretch(2,1)
        self.tab2.layout.setStretch(3,1)
        self.tab2.layout.setStretch(4,3)
        self.tab2.layout.setStretch(5,1)
        self.tab2.layout.setStretch(6,1)
        self.tab2.layout.setStretch(7,1)
        self.tab2.layout.setStretch(8,1)
        self.tab2.layout.setStretch(9,1)
        self.tab2.layout.setStretch(10,1)
        self.tab2.layout.setStretch(11,1)
        self.tab2.layout.setStretch(12,1)
        self.tab2.layout.setStretch(13,38)


        self.tab3.layout = QtWidgets.QVBoxLayout()
        self.tab3.layout.setSpacing(0)
        self.tab3.setLayout(self.tab3.layout)
        self.tab3.layout.addItem(spacerItem)#0

        self.exportLabel = QtWidgets.QLabel()
        self.exportLabel.setText('Export Configurations')
        self.exportLabel.setFont(font)
        self.exportLabel.setStyleSheet('color:white; margin-left: 10')
        self.tab3.layout.addWidget(self.exportLabel)
        self.tab3.layout.addItem(spacerItem)

        self.exportLayout = QtWidgets.QHBoxLayout()
        self.exportLayout.setSpacing(0)

        self.export = QtWidgets.QLabel()
        labelFont = QtGui.QFont()
        labelFont.setPointSize(14)
        self.export.setFont(labelFont)
        self.export.setStyleSheet("color:white")
        self.export.setText('Export Device Configuration: ')
        self.exportLayout.addItem(spacerItem)
        self.exportLayout.addWidget(self.export)
        self.exportLayout.addItem(spacerItem)

        self.exportButton = QtWidgets.QPushButton()
        self.exportButton.setText('Export')
        self.exportButton.setFont(labelFont)
        self.exportButton.setStyleSheet("""
            QPushButton{
                background-color: #4277BD;
                color: white;
                border-radius: 10px;
            }
            QPushButton:hover{
                background-color: #499DD0;
                border-radius:10px;
            }
        """)
        self.exportButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exportButton.setMaximumSize(QtCore.QSize(80,30))
        self.exportButton.setMinimumSize(QtCore.QSize(80,30))
        self.exportLayout.addWidget(self.exportButton)
        self.exportLayout.addItem(spacerItem)

        self.exportLayout.setStretch(0,2)
        self.exportLayout.setStretch(1,5)
        self.exportLayout.setStretch(2,2)
        self.exportLayout.setStretch(3,3)
        self.exportLayout.setStretch(4,40)

        self.tab3.layout.addLayout(self.exportLayout)
        self.tab3.layout.addItem(spacerItem)
        
        self.bakcupLabel = QtWidgets.QLabel()
        self.bakcupLabel.setText('Storage Settings')
        self.bakcupLabel.setFont(font)
        self.bakcupLabel.setStyleSheet('color:white;margin-left:10')
        self.tab3.layout.addWidget(self.bakcupLabel)#1
        self.tab3.layout.addItem(spacerItem)#2

        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem32)
        self.label_17 = QtWidgets.QLabel()
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color:white;")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_23.addWidget(self.label_17)
        
        self.path = QtWidgets.QLineEdit()
        self.path.setStyleSheet("background:#EEF4F9;border: 1px  solid #757475; margin-left:10px")
        self.path.setText("")
        self.path.setObjectName("path")
        self.horizontalLayout_23.addWidget(self.path)
        
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem33)
        self.pathButton = QtWidgets.QPushButton()
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pathButton.setFont(font)
        self.pathButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pathButton.setStyleSheet("QPushButton{\n"
"background:#3A3c41;color:white"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:lightgray;\n"
"    color:black;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:gray;\n"
"    color:white"
"}\n"
"")
        self.pathButton.setObjectName("pathButton")
        self.horizontalLayout_23.addWidget(self.pathButton)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem34)
        self.pathButton_2 = QtWidgets.QPushButton()
        font = QtGui.QFont()
        self.pathButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        font.setPointSize(14)
        self.pathButton_2.setFont(font)
        self.pathButton_2.setStyleSheet("QPushButton{\n"
"background:#3A3c41;color:white"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:lightgray;\n"
"    color:black;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:gray;\n"
"    color:white"
"}\n"
"")
        self.pathButton_2.setObjectName("pathButton_2")
        self.horizontalLayout_23.addWidget(self.pathButton_2)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem35)
        self.horizontalLayout_23.setStretch(0, 3)
        self.horizontalLayout_23.setStretch(1, 5)
        self.horizontalLayout_23.setStretch(2, 50)
        self.horizontalLayout_23.setStretch(3, 5)
        self.horizontalLayout_23.setStretch(4, 5)
        self.horizontalLayout_23.setStretch(5, 2)
        self.horizontalLayout_23.setStretch(6, 1)
        self.horizontalLayout_23.setStretch(7, 25)
        
        self.tab3.layout.addLayout(self.horizontalLayout_23) #3
        spacerItem36 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.tab3.layout.addItem(spacerItem36) #4
        
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem37)
        self.label_18 = QtWidgets.QLabel()
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color:white;")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_24.addWidget(self.label_18)
        self.cover = QtWidgets.QComboBox()
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cover.setFont(font)
        self.cover.setStyleSheet("""
                                QComboBox{
                                         background-color:white;
                                         color:black;
                                        }
                                
                                 """)
        self.cover.setObjectName("cover")
        self.cover.addItem("")
        self.cover.addItem("")
        self.horizontalLayout_24.addWidget(self.cover)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem38)
        self.horizontalLayout_24.setStretch(0, 1)
        self.horizontalLayout_24.setStretch(1, 1)
        self.horizontalLayout_24.setStretch(2, 4)
        self.horizontalLayout_24.setStretch(3, 24)
        self.tab3.layout.addLayout(self.horizontalLayout_24) #5
        spacerItem39 = QtWidgets.QSpacerItem(1058, 59, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.tab3.layout.addItem(spacerItem39) #6
        
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem40)
        
        self.start = QtWidgets.QPushButton()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        self.start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start.sizePolicy().hasHeightForWidth())
        self.start.setSizePolicy(sizePolicy)
        self.start.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.start.setFont(font)
        self.start.setStyleSheet("QPushButton{\n"
"background:#069CFF;color:black;border: 2px  solid #757475;;"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:lightblue;\n"
"    color:black;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:blue;\n"
"    color:white"
"}\n"
"")
        self.start.setObjectName("start")
        self.horizontalLayout_18.addWidget(self.start)
        spacerItem44 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem44)
        self.horizontalLayout_18.setStretch(0, 41)
        self.horizontalLayout_18.setStretch(1, 2)
        self.horizontalLayout_18.setStretch(2, 4)
        self.tab3.layout.addLayout(self.horizontalLayout_18) #7
        self.tab3.layout.addItem(spacerItem)#8

        self.tab3.layout.setStretch(0,1)
        self.tab3.layout.setStretch(1,1)
        self.tab3.layout.setStretch(2,1)
        self.tab3.layout.setStretch(3,1)
        self.tab3.layout.setStretch(4,1)
        self.tab3.layout.setStretch(5,1)
        self.tab3.layout.setStretch(6,1)
        self.tab3.layout.setStretch(7,1)
        self.tab3.layout.setStretch(8,1)
        self.tab3.layout.setStretch(9,1)
        self.tab3.layout.setStretch(10,20)
        self.tab3.layout.setStretch(11,1)
        self.tab3.layout.setStretch(12,1)

        self.verticalLayout_5.addWidget(self.tabs)

        self.horizontalLayout.addWidget(self.frame_2)
        self.horizontalLayout.setStretch(0,3)
        self.horizontalLayout.setStretch(1,20)
        self.horizontalLayout_11.addLayout(self.horizontalLayout)
        
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.verticalLayout_2.setStretch(0,1)
        self.verticalLayout_2.setStretch(1,80)

        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4.setStretch(0,80)
        

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_6.setIcon(QtGui.QIcon("home_white.png"))
        self.pushButton_6.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_8.setIcon(QtGui.QIcon("video.png"))
        self.pushButton_8.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_7.setIcon(QtGui.QIcon("settings_white.png"))
        self.pushButton_7.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_search.setIcon(QtGui.QIcon("search_pls.png"))
        self.pushButton_search.setIconSize(QtCore.QSize(85,85))
        
        self.label_23.setText(_translate("MainWindow", "設定"))
        self.pushButton_2.setText(_translate("MainWindow", "Camera Settings"))
        self.pushButton_0.setText(_translate("MainWindow", "Device Settings"))
        self.pushButton_3.setText(_translate("MainWindow", "功能設定"))
        self.pushButton_4.setText(_translate("MainWindow", "AI Settings"))
        self.pushButton_5.setText(_translate("MainWindow", "Log"))

        self.label_17.setText(_translate("MainWindow", "備份路徑"))
        self.pathButton.setText(_translate("MainWindow", " 瀏覽 "))
        self.pathButton_2.setText(_translate("MainWindow", "備份"))
        self.label_18.setText(_translate("MainWindow", "硬碟滿時"))
        self.cover.setItemText(0, _translate("MainWindow", "覆蓋"))
        self.cover.setItemText(1, _translate("MainWindow", "停止"))
        self.start.setText(_translate("MainWindow", "確定"))
        
        self.label_time.setText(_translate("MainWindow","Sync Every: "))
        self.satuan.setText(_translate("MainWindow", "Minutes"))
        self.asyncLabel.setText(_translate("MainWindow", "Enable Sync:"))
        self.TimeButton.setText(_translate("MainWindow", 'Set'))
        self.TimeLabel.setText(_translate("MainWindw", 'NTP Server'))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
