# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newsettingmain.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QRect
import sys
from components.mySwitch import MySwitch

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1120)
        MainWindow.setStyleSheet("background:black;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("background-image : url(images/background.png);")
        self.centralwidget.setObjectName("centralwidget")
        
        #############################################################################################################
        #############################################################################################################
        
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        
        self.label_10 = QtWidgets.QLabel(self.centralwidget) #logo
        self.label_10.setMaximumSize(QtCore.QSize(540, 95))
        self.label_10.setStyleSheet("background:blue")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("images/logoo.png"))
        self.label_10.setScaledContents(False)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10) #horizontal 0
        
        self.horizontalLayout_logo = QtWidgets.QHBoxLayout()
        self.horizontalLayout_logo.setSpacing(0)
        self.horizontalLayout_logo.setObjectName("HorizontalLayout_logo")
        
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget) #go back to menu
        self.pushButton_6.setToolTip('Home')
        self.pushButton_6.setMinimumSize(QtCore.QSize(80,80))
        self.pushButton_6.setMaximumSize(QtCore.QSize(80,80))
        self.pushButton_6.setStyleSheet("""
                                        QPushButton{
                                                background-color: black;
                                                color:white;
                                                border-radius:10px;
                                        }
                                        QPushButton:hover{
                                                background-color: #00BDFE;
                                        }
                                        QToolTip{
                                                background-color:black;
                                                color:white;
                                                border: transparent solid 0px;
                                        }
                                """)
        self.pushButton_6.setDefault(True)
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout_logo.addWidget(self.pushButton_6)
        
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_logo.addItem(spacerItem) 
        
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget) 
        self.pushButton_7.setToolTip("Camera")
        self.pushButton_7.setMinimumSize(QtCore.QSize(80,80))
        self.pushButton_7.setMaximumSize(QtCore.QSize(80,80))
        self.pushButton_7.setStyleSheet("""
                                        QPushButton{
                                                background-color: #00BDFE;
                                                color:white;
                                                border-radius:10px;
                                        }
                                        QPushButton:hover{
                                                background-color: #00BDFE;
                                        }
                                        QToolTip{
                                                background-color:black;
                                                color:white;
                                                border: transparent solid 0px;
                                        }
                                """)
        self.pushButton_7.setDefault(True)
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout_logo.addWidget(self.pushButton_7) 
        
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_logo.addItem(spacerItem1) 

        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget) #gotosettings
        self.pushButton_8.setToolTip("Settings")
        self.pushButton_8.setMinimumSize(QtCore.QSize(80,80))
        self.pushButton_8.setMaximumSize(QtCore.QSize(80,80))
        self.pushButton_8.setStyleSheet("""
                                        QPushButton{
                                                background-color: black;
                                                color:white;
                                                border-radius:10px;
                                        }
                                        QPushButton:hover{
                                                background-color: #00BDFE;
                                        }
                                """)
        self.pushButton_8.setDefault(True)
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout_logo.addWidget(self.pushButton_8) 
        
        self.horizontalLayout_logo.addItem(spacerItem)
        
        self.pushButton_search = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_search.setMinimumSize(QtCore.QSize(80,80))
        self.pushButton_search.setMaximumSize(QtCore.QSize(80,80))
        self.pushButton_search.setStyleSheet("""
                                        QPushButton{
                                                background-color: black;
                                                color:white;
                                                border-radius:10px;
                                        }
                                        QPushButton:hover{
                                                background-color: #00BDFE;
                                        }
                                """)
        self.pushButton_search.setDefault(True)
        self.pushButton_search.setFlat(True)
        self.pushButton_search.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_search.setObjectName("PushButton_search")
        self.horizontalLayout_logo.addWidget(self.pushButton_search)
        
        self.horizontalLayout_logo.addItem(spacerItem)
        
        self.horizontalLayout_logo.setStretch(0,10)
        self.horizontalLayout_logo.setStretch(1,1)
        self.horizontalLayout_logo.setStretch(2,9)
        self.horizontalLayout_logo.setStretch(3,1)
        self.horizontalLayout_logo.setStretch(4,9)
        self.horizontalLayout_logo.setStretch(5,1)
        self.horizontalLayout_logo.setStretch(6,9)
        self.horizontalLayout_logo.setStretch(8,10)
        
        self.horizontalLayout_5.addLayout(self.horizontalLayout_logo) #horizontal -2
        
        
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3) #horizontal -3
        
        self.label_23 = QtWidgets.QLabel(self.centralwidget) #tanda window
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK TC")
        font.setPointSize(20)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color:#707070;")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_5.addWidget(self.label_23) #horizontal -4
        
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4) #horizontal - 5
        
        self.ppe = QtWidgets.QPushButton(self.centralwidget)#logo
        self.ppe.setMaximumSize(QtCore.QSize(60, 60))
        self.ppe.setAutoFillBackground(False)
        self.ppe.setStyleSheet("border-radius: 15px;")
        self.ppe.setText("")
        self.ppe.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/Group 104.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ppe.setIcon(icon)
        self.ppe.setIconSize(QtCore.QSize(60, 60))
        self.ppe.setObjectName("ppe")
        
        self.horizontalLayout_5.addWidget(self.ppe) #horizontal - 6
        
        
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5) #horizontal - 7
        
        self.horizontalLayout_5.setStretch(0, 3)
        self.horizontalLayout_5.setStretch(1, 80)
        self.horizontalLayout_5.setStretch(2, 10)
        self.horizontalLayout_5.setStretch(3, 1)
        self.horizontalLayout_5.setStretch(4, 1)
        self.horizontalLayout_5.setStretch(5, 1)
        self.horizontalLayout_5.setStretch(6, 2)
        
        
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        
        #############################################################################################################
        #############################################################################################################
        #settings kiri
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background:#121E28;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        
        
        self.pushButton_2 = QtWidgets.QPushButton(self.frame) #settings 1 and 2
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background:#3A3C41;\n"
"color:white;")
        self.pushButton_2.setObjectName("pushButton_2") #gong neng
        self.verticalLayout.addWidget(self.pushButton_2)
        
        self.pushButton_0 = QtWidgets.QPushButton(self.frame) #settings 1 and 2
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_0.setStyleSheet("color:white;")
        self.pushButton_0.setObjectName("pushButton_0") #gong neng
        self.verticalLayout.addWidget(self.pushButton_0)
        
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("color:white;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)#belum ke isi
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setAutoFillBackground(False)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("color:white;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)

        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setAutoFillBackground(False)
        self.pushButton_5.setStyleSheet('color: white')
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.verticalLayout.addWidget(self.pushButton_5)

        self.pushButtonReset = QtWidgets.QPushButton(self.frame)
        self.pushButtonReset.setText('Factory Reset')
        self.pushButtonReset.setFont(font)
        self.pushButtonReset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonReset.setAutoFillBackground(False)
        self.pushButtonReset.setStyleSheet('color: white')
        self.verticalLayout.addWidget(self.pushButtonReset, alignment = QtCore.Qt.AlignBottom)
        
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        
        self.verticalLayout_4.addLayout(self.verticalLayout)
        
        self.horizontalLayout.addWidget(self.frame)

        self.horizontalSync = QtWidgets.QHBoxLayout()
        self.horizontalSync.setSpacing(0)
        self.horizontalSync.setObjectName('horizontalSync')

        self.horizontalSync.addItem(spacerItem)
        self.syncLabel = QtWidgets.QLabel()
        self.syncLabel.setText('Set Backend Settings: ')
        self.syncLabel.setStyleSheet('color:red')
        self.horizontalSync.addWidget(self.syncLabel)

        self.sync = MySwitch()
        self.sync.setChecked(True)
        self.sync.setObjectName('sycn')
        self.horizontalSync.addWidget(self.sync)
        self.horizontalSync.addItem(spacerItem)

        self.horizontalSync.setStretch(0,10)
        self.horizontalSync.setStretch(1,3)
        self.horizontalSync.setStretch(2,3)
        self.horizontalSync.setStretch(3,10)
        
        #############################################################################################################
        #############################################################################################################
        #main settings
        
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background:black")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")

        
        #############################################################################################################
        #############################################################################################################
        #main table
        spacerItem10 = QtWidgets.QSpacerItem(1058, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addLayout(self.horizontalSync)
        
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem11)
        
        self.frame_4 = QtWidgets.QFrame(self.frame_2) #frame 4
        self.frame_4.setStyleSheet("#frame_4{border: 2px  solid #757475;}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        
        self.label_6 = QtWidgets.QLabel(self.frame_4) #label channel 1
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background:#3A3C41;color:white;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem12)
        
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        
        self.label_15 = QtWidgets.QLabel(self.frame_4) #first label input : place
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_15.setFont(font)
        self.label_15.setAutoFillBackground(False)
        self.label_15.setStyleSheet("color:white;margin-left:10")
        self.label_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_15.setLineWidth(1)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_17.addWidget(self.label_15)
        
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem13)
        
        self.place1 = QtWidgets.QLineEdit(self.frame_4)#first input: plaace
        font = QtGui.QFont()
        font.setPointSize(14)
        self.place1.setFont(font)
        self.place1.setStyleSheet("color:#7D7C7C;border: 1px solid #757475; margin-right:10")
        self.place1.setObjectName("place1")
        self.horizontalLayout_17.addWidget(self.place1)
        
        self.horizontalLayout_17.setStretch(0, 1)
        self.horizontalLayout_17.setStretch(1, 2)
        self.horizontalLayout_17.setStretch(2, 29)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        
        
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem14)
        
        
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout() #IP
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        
        self.label_7 = QtWidgets.QLabel(self.frame_4)#label input : IP
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setAutoFillBackground(False)
        self.label_7.setStyleSheet("color:white;margin-left:10")
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_7.setLineWidth(1)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7) 
        
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem15)
        
        self.ip1 = QtWidgets.QLineEdit(self.frame_4) #input : IP
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ip1.setFont(font)
        self.ip1.setStyleSheet("color:#7D7C7C;border: 1px  solid #757475;margin-right:10")
        self.ip1.setObjectName("ip1")
        self.horizontalLayout_7.addWidget(self.ip1)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 1)
        self.horizontalLayout_7.setStretch(2, 30)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7) 
        
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem16)
        
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        
        self.label_8 = QtWidgets.QLabel(self.frame_4) #label input: name
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:white;margin-left:10")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem17)
        
        self.password1 = QtWidgets.QLineEdit(self.frame_4) #input: name
        font = QtGui.QFont()
        font.setPointSize(14)
        self.password1.setFont(font)
        self.password1.setStyleSheet("color:#7D7C7C;border: 1px  solid #757475;margin-right:10")
        self.password1.setObjectName("password1")
        self.horizontalLayout_9.addWidget(self.password1)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 1)
        self.horizontalLayout_9.setStretch(2, 30)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem18)
        
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        
        self.label_9 = QtWidgets.QLabel(self.frame_4) #label input: password
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:white;margin-left:10")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem19)
        
        self.password1_2 = QtWidgets.QLineEdit(self.frame_4) #input: password
        font = QtGui.QFont()
        font.setPointSize(14)
        self.password1_2.setFont(font)
        self.password1_2.setStyleSheet("color:#7D7C7C;border: 1px  solid #757475;margin-right:10")
        self.password1_2.setObjectName("password1_2")
        self.password1_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.horizontalLayout_12.addWidget(self.password1_2)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 2)
        self.horizontalLayout_12.setStretch(2, 29)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem20)
        
        #horizontal layout for ROI
        self.horizontalLayout_ROI = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ROI.setObjectName("Horizontal Layout ROI")
        
        spacerItem_ROI = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        
        self.label_ROI = QtWidgets.QLabel(self.frame_4) #label input: password
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_ROI.setFont(font)
        self.label_ROI.setStyleSheet("color:white;margin-left:10")
        self.label_ROI.setObjectName("label_9")
        self.horizontalLayout_ROI.addWidget(self.label_ROI) #input label: ROI #0
        
        self.horizontalLayout_ROI.addItem(spacerItem_ROI) #1
        
        #on button
        self.ROI_onButton = MySwitch()
        self.ROI_onButton.setChecked(True)
        self.ROI_onButton.setObjectName("ROI_onButton")
        self.horizontalLayout_ROI.addWidget(self.ROI_onButton) #2
        
        self.horizontalLayout_ROI.addItem(spacerItem_ROI) #5
        
        self.horizontalLayout_ROI.setStretch(0,2)
        self.horizontalLayout_ROI.setStretch(1,1)
        self.horizontalLayout_ROI.setStretch(2,10)
        self.horizontalLayout_ROI.setStretch(3,20)
        
        self.verticalLayout_6.addLayout(self.horizontalLayout_ROI)
        
        self.verticalLayout_6.addItem(spacerItem20)
        
        self.horizontalLayout_IO = QtWidgets.QHBoxLayout()
        self.horizontalLayout_IO.setSpacing(0)
        self.horizontalLayout_IO.setObjectName("HorizontalLayout_IO")
        
        self.label_IO = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_IO.setFont(font)
        self.label_IO.setStyleSheet("color:white;")
        self.label_IO.setStyleSheet("background-color: black; color: white;margin-left:10")
        self.label_IO.setObjectName("label_IO")
        
        self.horizontalLayout_IO.addWidget(self.label_IO)
        self.horizontalLayout_IO.addItem(spacerItem)
        
        self.toggle_IO = MySwitch()
        self.toggle_IO.setChecked(True)
        self.horizontalLayout_IO.addWidget(self.toggle_IO)
        self.horizontalLayout_IO.addItem(spacerItem)

        self.horizontalLayout_IO.setStretch(0,5)
        self.horizontalLayout_IO.setStretch(1,1)
        self.horizontalLayout_IO.setStretch(2,5)
        self.horizontalLayout_IO.setStretch(3,20)

        self.verticalLayout_6.addLayout(self.horizontalLayout_IO)
        self.verticalLayout_6.addItem(spacerItem)
                
        self.verticalLayout_6.setStretch(0, 12)
        self.verticalLayout_6.setStretch(1, 1)
        self.verticalLayout_6.setStretch(2, 15)
        self.verticalLayout_6.setStretch(3, 1)
        self.verticalLayout_6.setStretch(4, 15)
        self.verticalLayout_6.setStretch(5, 1)
        self.verticalLayout_6.setStretch(6, 15)
        self.verticalLayout_6.setStretch(7, 1)
        self.verticalLayout_6.setStretch(8, 15)
        self.verticalLayout_6.setStretch(9, 1)
        self.verticalLayout_6.setStretch(10, 15)
        self.verticalLayout_6.setStretch(11, 1)
        self.verticalLayout_6.setStretch(12, 15)
        self.verticalLayout_6.setStretch(13, 1)
        self.horizontalLayout_8.addLayout(self.verticalLayout_6)
        self.horizontalLayout_10.addWidget(self.frame_4)
        
        #############################################################################################################
        #############################################################################################################
        #second main Table
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setStyleSheet("#frame_5{border: 2px  solid #757475;}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.frame_5)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background:#3A3C41;color:white;")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_7.addWidget(self.label_11)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem21)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_19 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_19.setFont(font)
        self.label_19.setAutoFillBackground(False)
        self.label_19.setStyleSheet("color:white;margin-left:10")
        self.label_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_19.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_19.setLineWidth(1)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_19.addWidget(self.label_19)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem22)
        self.place2 = QtWidgets.QLineEdit(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.place2.setFont(font)
        self.place2.setStyleSheet("color:#7D7C7C;border: 1px  solid #757475;margin-right:10")
        self.place2.setObjectName("place2")
        self.horizontalLayout_19.addWidget(self.place2)
        self.horizontalLayout_19.setStretch(0, 1)
        self.horizontalLayout_19.setStretch(1, 2)
        self.horizontalLayout_19.setStretch(2, 29)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem23)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_12 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setAutoFillBackground(False)
        self.label_12.setStyleSheet("color:white;margin-left:10")
        self.label_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_12.setLineWidth(1)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_14.addWidget(self.label_12)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem24)
        self.ip2 = QtWidgets.QLineEdit(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ip2.setFont(font)
        self.ip2.setStyleSheet("color:#7D7C7C;border: 1px  solid #757475;margin-right:10")
        self.ip2.setObjectName("ip2")
        self.horizontalLayout_14.addWidget(self.ip2)
        self.horizontalLayout_14.setStretch(0, 1)
        self.horizontalLayout_14.setStretch(1, 1)
        self.horizontalLayout_14.setStretch(2, 30)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem25)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_13 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color:white;margin-left:10")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_15.addWidget(self.label_13)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem26)
        self.password3 = QtWidgets.QLineEdit(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.password3.setFont(font)
        self.password3.setStyleSheet("color:#7D7C7C;border: 1px  solid #757475;margin-right:10")
        self.password3.setObjectName("password3")
        self.horizontalLayout_15.addWidget(self.password3)
        self.horizontalLayout_15.setStretch(0, 1)
        self.horizontalLayout_15.setStretch(1, 1)
        self.horizontalLayout_15.setStretch(2, 30)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem27)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_14 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color:white;margin-left:10")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_16.addWidget(self.label_14)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem28)
        self.password4 = QtWidgets.QLineEdit(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.password4.setFont(font)
        self.password4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password4.setStyleSheet("color:#7D7C7C;border: 1px  solid #757475;margin-right:10")
        self.password4.setObjectName("password4")
        self.horizontalLayout_16.addWidget(self.password4)
        self.horizontalLayout_16.setStretch(0, 1)
        self.horizontalLayout_16.setStretch(1, 2)
        self.horizontalLayout_16.setStretch(2, 29)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem29)
        
        #horizontal layout for ROI
        self.horizontalLayout_ROI2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ROI2.setObjectName("Horizontal Layout ROI")
        
        self.label_ROI2 = QtWidgets.QLabel(self.frame_5) #label input: password
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_ROI2.setFont(font)
        self.label_ROI2.setStyleSheet("color:white;margin-left:10")
        self.label_ROI2.setObjectName("label_9")
        self.horizontalLayout_ROI2.addWidget(self.label_ROI2) #input label: ROI #0
        
        self.horizontalLayout_ROI2.addItem(spacerItem_ROI) #1
        
        #on button
        self.ROI_onButton2 = MySwitch()
        self.ROI_onButton2.setChecked(True)
        self.ROI_onButton2.setObjectName("ROI_onButton2")
        self.horizontalLayout_ROI2.addWidget(self.ROI_onButton2) #2
        
        self.horizontalLayout_ROI2.addItem(spacerItem_ROI) #5
        
        self.horizontalLayout_ROI2.setStretch(0,2)
        self.horizontalLayout_ROI2.setStretch(1,1)
        self.horizontalLayout_ROI2.setStretch(2,10)
        self.horizontalLayout_ROI2.setStretch(3,20)
        
        self.verticalLayout_7.addLayout(self.horizontalLayout_ROI2)
        self.verticalLayout_7.addItem(spacerItem20)
        
        self.horizontalLayout_IO_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_IO_2.setSpacing(0)
        self.horizontalLayout_IO_2.setObjectName("HorizontalLayout_IO")
        
        self.label_IO_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_IO_2.setFont(font)
        self.label_IO_2.setStyleSheet("color:white;")
        self.label_IO_2.setStyleSheet("background-color: black; color: white;margin-left:10")
        self.label_IO_2.setObjectName("label_IO")
        
        self.horizontalLayout_IO_2.addWidget(self.label_IO_2)
        self.horizontalLayout_IO_2.addItem(spacerItem)
        
        self.toggle_IO_2 = MySwitch()
        self.toggle_IO_2.setChecked(True)
        self.horizontalLayout_IO_2.addWidget(self.toggle_IO_2)
        self.horizontalLayout_IO_2.addItem(spacerItem)

        self.horizontalLayout_IO_2.setStretch(0,5)
        self.horizontalLayout_IO_2.setStretch(1,1)
        self.horizontalLayout_IO_2.setStretch(2,5)
        self.horizontalLayout_IO_2.setStretch(3,20)

        self.verticalLayout_7.addLayout(self.horizontalLayout_IO_2)
        self.verticalLayout_7.addItem(spacerItem)
        
        self.verticalLayout_7.setStretch(0, 12)
        self.verticalLayout_7.setStretch(1, 1)
        self.verticalLayout_7.setStretch(2, 15)
        self.verticalLayout_7.setStretch(3, 1)
        self.verticalLayout_7.setStretch(4, 15)
        self.verticalLayout_7.setStretch(5, 1)
        self.verticalLayout_7.setStretch(6, 15)
        self.verticalLayout_7.setStretch(7, 1)
        self.verticalLayout_7.setStretch(8, 15)
        self.verticalLayout_7.setStretch(9, 1)
        self.verticalLayout_7.setStretch(10, 15)
        self.verticalLayout_7.setStretch(11, 1)
        self.verticalLayout_7.setStretch(12, 15)
        self.verticalLayout_7.setStretch(13, 1)

        self.horizontalLayout_13.addLayout(self.verticalLayout_7)
        self.horizontalLayout_10.addWidget(self.frame_5)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem30)
        self.horizontalLayout_10.setStretch(0, 2)
        self.horizontalLayout_10.setStretch(1, 7)
        self.horizontalLayout_10.setStretch(2, 7)
        self.horizontalLayout_10.setStretch(3, 2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)#1
        
        
        #############################################################################################################
        #############################################################################################################
        
        
        #main table
        
        self.horizontalLayout_101 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_101.setSpacing(0)
        self.horizontalLayout_101.setObjectName("horizontalLayout_10")
        
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_101.addItem(spacerItem11)
        
        self.frame_6 = QtWidgets.QFrame(self.frame_2) #frame 4
        self.frame_6.setStyleSheet("#frame_4{border: 2px  solid #757475;}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_4")
        
        self.horizontalLayout_81 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_81.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_81.setSpacing(0)
        self.horizontalLayout_81.setObjectName("horizontalLayout_8")
        self.verticalLayout_61 = QtWidgets.QVBoxLayout()
        self.verticalLayout_61.setObjectName("verticalLayout_6")
        
        self.label_61 = QtWidgets.QLabel(self.frame_6) #label channel 1
        self.label_61.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_61.setFont(font)
        self.label_61.setStyleSheet("background:#3A3C41;color:white;")
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName("label_6")
        self.verticalLayout_61.addWidget(self.label_61)
        
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_61.addItem(spacerItem12)
        
        self.horizontalLayout_171 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_171.setObjectName("horizontalLayout_17")
        
        self.label_151 = QtWidgets.QLabel(self.frame_6) #first label input : place
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_151.setFont(font)
        self.label_151.setAutoFillBackground(False)
        self.label_151.setStyleSheet("color:white;margin-left:10")
        self.label_151.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_151.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_151.setLineWidth(1)
        self.label_151.setObjectName("label_15")
        self.horizontalLayout_171.addWidget(self.label_151)
        
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_171.addItem(spacerItem13)
        
        self.place3 = QtWidgets.QLineEdit(self.frame_6)#first input: plaace
        font = QtGui.QFont()
        font.setPointSize(14)
        self.place3.setFont(font)
        self.place3.setStyleSheet("color:#7D7C7C;border: 1px  solid #757475;margin-right:10")
        self.place3.setObjectName("place1")
        self.horizontalLayout_171.addWidget(self.place3)
        
        self.horizontalLayout_171.setStretch(0, 1)
        self.horizontalLayout_171.setStretch(1, 2)
        self.horizontalLayout_171.setStretch(2, 29)
        self.verticalLayout_61.addLayout(self.horizontalLayout_171)
        
        
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_61.addItem(spacerItem14)
        
        
        self.horizontalLayout_71 = QtWidgets.QHBoxLayout() #IP
        self.horizontalLayout_71.setObjectName("horizontalLayout_7")
        
        self.label_71 = QtWidgets.QLabel(self.frame_6)#label input : IP
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_71.setFont(font)
        self.label_71.setAutoFillBackground(False)
        self.label_71.setStyleSheet("color:white;margin-left:10")
        self.label_71.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_71.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_71.setLineWidth(1)
        self.label_71.setObjectName("label_71")
        self.horizontalLayout_71.addWidget(self.label_71) 
        
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_71.addItem(spacerItem15)
        
        self.ip3 = QtWidgets.QLineEdit(self.frame_6) #input : IP
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ip3.setFont(font)
        self.ip3.setStyleSheet("color:#7D7C7C;border: 1px  solid #757475;margin-right:10")
        self.ip3.setObjectName("ip1")
        self.horizontalLayout_71.addWidget(self.ip3)
        self.horizontalLayout_71.setStretch(0, 1)
        self.horizontalLayout_71.setStretch(1, 1)
        self.horizontalLayout_71.setStretch(2, 30)
        self.verticalLayout_61.addLayout(self.horizontalLayout_71) 
        
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_61.addItem(spacerItem16)
        
        self.horizontalLayout_91 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_91.setObjectName("horizontalLayout_91")
        
        self.label_81 = QtWidgets.QLabel(self.frame_6) #label input: name
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_81.setFont(font)
        self.label_81.setStyleSheet("color:white;margin-left:10")
        self.label_81.setObjectName("label_8")
        self.horizontalLayout_91.addWidget(self.label_81)
        
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_91.addItem(spacerItem17)
        
        self.password_new1 = QtWidgets.QLineEdit(self.frame_6) #input: name
        font = QtGui.QFont()
        font.setPointSize(14)
        self.password_new1.setFont(font)
        self.password_new1.setStyleSheet("color:#7D7C7C;border: 1px  solid #757475;margin-right:10")
        self.password_new1.setObjectName("password1")
        self.horizontalLayout_91.addWidget(self.password_new1)
        self.horizontalLayout_91.setStretch(0, 1)
        self.horizontalLayout_91.setStretch(1, 1)
        self.horizontalLayout_91.setStretch(2, 30)
        self.verticalLayout_61.addLayout(self.horizontalLayout_91)
        
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_61.addItem(spacerItem18)
        
        self.horizontalLayout_121 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_121.setObjectName("horizontalLayout_12")
        
        self.label_91 = QtWidgets.QLabel(self.frame_6) #label input: password
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_91.setFont(font)
        self.label_91.setStyleSheet("color:white;margin-left:10")
        self.label_91.setObjectName("label_9")
        self.horizontalLayout_121.addWidget(self.label_91)
        
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_121.addItem(spacerItem19)
        
        self.password1_new2 = QtWidgets.QLineEdit(self.frame_6) #input: password
        font = QtGui.QFont()
        font.setPointSize(14)
        self.password1_new2.setFont(font)
        self.password1_new2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password1_new2.setStyleSheet("color:#7D7C7C;border: 1px  solid #757475;margin-right:10")
        self.password1_new2.setObjectName("password1_new2")
        self.horizontalLayout_121.addWidget(self.password1_new2)
        self.horizontalLayout_121.setStretch(0, 1)
        self.horizontalLayout_121.setStretch(1, 2)
        self.horizontalLayout_121.setStretch(2, 29)
        self.verticalLayout_61.addLayout(self.horizontalLayout_121)
        
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_61.addItem(spacerItem20)
        
        #horizontal layout for ROI
        self.horizontalLayout_ROI_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ROI_3.setObjectName("Horizontal Layout ROI")
        
        self.label_ROI_3 = QtWidgets.QLabel(self.frame_6) #label input: password
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_ROI_3.setFont(font)
        self.label_ROI_3.setStyleSheet("color:white;margin-left:10")
        self.label_ROI_3.setObjectName("label_9")
        self.horizontalLayout_ROI_3.addWidget(self.label_ROI_3) #input label: ROI #0
        
        self.horizontalLayout_ROI_3.addItem(spacerItem_ROI) #1
        
        #on button
        self.ROI_onButton_3 = MySwitch()
        self.ROI_onButton_3.setChecked(True)
        self.ROI_onButton_3.setObjectName("ROI_onButton_3")
        self.horizontalLayout_ROI_3.addWidget(self.ROI_onButton_3) #2
        
        self.horizontalLayout_ROI_3.addItem(spacerItem_ROI) #5
        
        self.horizontalLayout_ROI_3.setStretch(0,2)
        self.horizontalLayout_ROI_3.setStretch(1,1)
        self.horizontalLayout_ROI_3.setStretch(2,10)
        self.horizontalLayout_ROI_3.setStretch(3,20)
        
        self.verticalLayout_61.addLayout(self.horizontalLayout_ROI_3)
        
        self.verticalLayout_61.addItem(spacerItem20)
        
        self.horizontalLayout_IO_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_IO_3.setSpacing(0)
        self.horizontalLayout_IO_3.setObjectName("HorizontalLayout_IO")
        
        self.label_IO_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_IO_3.setFont(font)
        self.label_IO_3.setStyleSheet("color:white;margin-left:10")
        self.label_IO_3.setStyleSheet("background-color: black; color: white;margin-left:10")
        self.label_IO_3.setObjectName("label_IO_3")
        
        self.horizontalLayout_IO_3.addWidget(self.label_IO_3)
        self.horizontalLayout_IO_3.addItem(spacerItem)
        
        self.toggle_IO_3 = MySwitch()
        self.toggle_IO_3.setChecked(True)
        self.horizontalLayout_IO_3.addWidget(self.toggle_IO_3)
        self.horizontalLayout_IO_3.addItem(spacerItem)

        self.horizontalLayout_IO_3.setStretch(0,5)
        self.horizontalLayout_IO_3.setStretch(1,1)
        self.horizontalLayout_IO_3.setStretch(2,5)
        self.horizontalLayout_IO_3.setStretch(3,20)

        self.verticalLayout_61.addLayout(self.horizontalLayout_IO_3)
        self.verticalLayout_61.addItem(spacerItem)
                
        self.verticalLayout_61.setStretch(0, 12)
        self.verticalLayout_61.setStretch(1, 1)
        self.verticalLayout_61.setStretch(2, 15)
        self.verticalLayout_61.setStretch(3, 1)
        self.verticalLayout_61.setStretch(4, 15)
        self.verticalLayout_61.setStretch(5, 1)
        self.verticalLayout_61.setStretch(6, 15)
        self.verticalLayout_61.setStretch(7, 1)
        self.verticalLayout_61.setStretch(8, 15)
        self.verticalLayout_61.setStretch(9, 1)
        self.verticalLayout_61.setStretch(10, 15)
        self.verticalLayout_61.setStretch(11, 1)
        self.verticalLayout_61.setStretch(12, 15)
        self.verticalLayout_61.setStretch(13, 1)
        self.horizontalLayout_81.addLayout(self.verticalLayout_61)
        self.horizontalLayout_101.addWidget(self.frame_6)
        
        #############################################################################################################
        #############################################################################################################
        #second main Table
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        self.frame_7.setStyleSheet("#frame_7{border: 2px  solid #757475;}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_131 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_131.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_131.setSpacing(0)
        self.horizontalLayout_131.setObjectName("horizontalLayout_13")
        self.verticalLayout_71 = QtWidgets.QVBoxLayout()
        self.verticalLayout_71.setObjectName("verticalLayout_7")
        self.label_111 = QtWidgets.QLabel(self.frame_7)
        self.label_111.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_111.setFont(font)
        self.label_111.setStyleSheet("background:#3A3C41;color:white;")
        self.label_111.setAlignment(QtCore.Qt.AlignCenter)
        self.label_111.setObjectName("label_111")
        self.verticalLayout_71.addWidget(self.label_111)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_71.addItem(spacerItem21)
        self.horizontalLayout_191 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_191.setObjectName("horizontalLayout_19")
        self.label_191 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_191.setFont(font)
        self.label_191.setAutoFillBackground(False)
        self.label_191.setStyleSheet("color:white;margin-left:10")
        self.label_191.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_191.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_191.setLineWidth(1)
        self.label_191.setObjectName("label_19")
        self.horizontalLayout_191.addWidget(self.label_191)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_191.addItem(spacerItem22)
        self.place4 = QtWidgets.QLineEdit(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.place4.setFont(font)
        self.place4.setStyleSheet("color:#7D7C7C;border: 1px  solid #757475;margin-right:10")
        self.place4.setObjectName("place4")
        self.horizontalLayout_191.addWidget(self.place4)
        self.horizontalLayout_191.setStretch(0, 1)
        self.horizontalLayout_191.setStretch(1, 2)
        self.horizontalLayout_191.setStretch(2, 29)
        self.verticalLayout_71.addLayout(self.horizontalLayout_191)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_71.addItem(spacerItem23)
        self.horizontalLayout_141 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_141.setObjectName("horizontalLayout_14")
        self.label_121 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_121.setFont(font)
        self.label_121.setAutoFillBackground(False)
        self.label_121.setStyleSheet("color:white;margin-left:10")
        self.label_121.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_121.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_121.setLineWidth(1)
        self.label_121.setObjectName("label_12")
        self.horizontalLayout_141.addWidget(self.label_121)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_141.addItem(spacerItem24)
        self.ip4 = QtWidgets.QLineEdit(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ip4.setFont(font)
        self.ip4.setStyleSheet("color:#7D7C7C;border: 1px  solid #757475;margin-right:10")
        self.ip4.setObjectName("ip2")
        self.horizontalLayout_141.addWidget(self.ip4)
        self.horizontalLayout_141.setStretch(0, 1)
        self.horizontalLayout_141.setStretch(1, 1)
        self.horizontalLayout_141.setStretch(2, 30)
        self.verticalLayout_71.addLayout(self.horizontalLayout_141)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_71.addItem(spacerItem25)
        self.horizontalLayout_151 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_151.setObjectName("horizontalLayout_15")
        self.label_131 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_131.setFont(font)
        self.label_131.setStyleSheet("color:white;margin-left:10")
        self.label_131.setObjectName("label_131")
        self.horizontalLayout_151.addWidget(self.label_131)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_151.addItem(spacerItem26)
        self.password_new3 = QtWidgets.QLineEdit(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.password_new3.setFont(font)
        self.password_new3.setStyleSheet("color:#7D7C7C;border: 1px  solid #757475;margin-right:10")
        self.password_new3.setObjectName("password3")
        self.horizontalLayout_151.addWidget(self.password_new3)
        self.horizontalLayout_151.setStretch(0, 1)
        self.horizontalLayout_151.setStretch(1, 1)
        self.horizontalLayout_151.setStretch(2, 30)
        self.verticalLayout_71.addLayout(self.horizontalLayout_151)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_71.addItem(spacerItem27)
        self.horizontalLayout_161 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_161.setObjectName("horizontalLayout_161")
        self.label_141 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_141.setFont(font)
        self.label_141.setStyleSheet("color:white;margin-left:10")
        self.label_141.setObjectName("label_141")
        self.horizontalLayout_161.addWidget(self.label_141)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_161.addItem(spacerItem28)
        self.password_new4 = QtWidgets.QLineEdit(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.password_new4.setFont(font)
        self.password_new4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_new4.setStyleSheet("color:#7D7C7C;border: 1px  solid #757475;margin-right:10")
        self.password_new4.setObjectName("password4")
        self.horizontalLayout_161.addWidget(self.password_new4)
        self.horizontalLayout_161.setStretch(0, 1)
        self.horizontalLayout_161.setStretch(1, 2)
        self.horizontalLayout_161.setStretch(2, 29)
        self.verticalLayout_71.addLayout(self.horizontalLayout_161)
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_71.addItem(spacerItem29)
        
        #horizontal layout for ROI
        self.horizontalLayout_ROI_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ROI_4.setObjectName("Horizontal Layout ROI")
        
        self.label_ROI_4 = QtWidgets.QLabel(self.frame_7) #label input: password
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_ROI_4.setFont(font)
        self.label_ROI_4.setStyleSheet("color:white;margin-left:10")
        self.label_ROI_4.setObjectName("label_9")
        self.horizontalLayout_ROI_4.addWidget(self.label_ROI_4) #input label: ROI #0
        
        self.horizontalLayout_ROI_4.addItem(spacerItem_ROI) #1
        
        #on button
        self.ROI_onButton_4 = MySwitch()
        self.ROI_onButton_4.setChecked(True)
        self.ROI_onButton_4.setObjectName("ROI_onButton4")
        self.horizontalLayout_ROI_4.addWidget(self.ROI_onButton_4) #2
        
        self.horizontalLayout_ROI_4.addItem(spacerItem_ROI) #5
        
        self.horizontalLayout_ROI_4.setStretch(0,2)
        self.horizontalLayout_ROI_4.setStretch(1,1)
        self.horizontalLayout_ROI_4.setStretch(2,10)
        self.horizontalLayout_ROI_4.setStretch(3,20)
        
        self.verticalLayout_71.addLayout(self.horizontalLayout_ROI_4)
        self.verticalLayout_71.addItem(spacerItem20)
        
        self.horizontalLayout_IO_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_IO_4.setSpacing(0)
        self.horizontalLayout_IO_4.setObjectName("HorizontalLayout_IO")
        
        self.label_IO_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_IO_4.setFont(font)
        self.label_IO_4.setStyleSheet("color:white;")
        self.label_IO_4.setStyleSheet("background-color: black; color: white;margin-left:10")
        self.label_IO_4.setObjectName("label_IO_4")
        
        self.horizontalLayout_IO_4.addWidget(self.label_IO_4)
        self.horizontalLayout_IO_4.addItem(spacerItem)
        
        self.toggle_IO_4 = MySwitch()
        self.toggle_IO_4.setChecked(True)
        self.horizontalLayout_IO_4.addWidget(self.toggle_IO_4)
        self.horizontalLayout_IO_4.addItem(spacerItem)

        self.horizontalLayout_IO_4.setStretch(0,5)
        self.horizontalLayout_IO_4.setStretch(1,1)
        self.horizontalLayout_IO_4.setStretch(2,5)
        self.horizontalLayout_IO_4.setStretch(3,20)

        self.verticalLayout_71.addLayout(self.horizontalLayout_IO_4)
        self.verticalLayout_71.addItem(spacerItem)
        
        self.verticalLayout_71.setStretch(0, 12)
        self.verticalLayout_71.setStretch(1, 1)
        self.verticalLayout_71.setStretch(2, 15)
        self.verticalLayout_71.setStretch(3, 1)
        self.verticalLayout_71.setStretch(4, 15)
        self.verticalLayout_71.setStretch(5, 1)
        self.verticalLayout_71.setStretch(6, 15)
        self.verticalLayout_71.setStretch(7, 1)
        self.verticalLayout_71.setStretch(8, 15)
        self.verticalLayout_71.setStretch(9, 1)
        self.verticalLayout_71.setStretch(10, 15)
        self.verticalLayout_71.setStretch(11, 1)
        self.verticalLayout_71.setStretch(12, 15)
        self.verticalLayout_71.setStretch(13, 1)

        self.horizontalLayout_131.addLayout(self.verticalLayout_71)
        self.horizontalLayout_101.addWidget(self.frame_7)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_101.addItem(spacerItem30)
        self.horizontalLayout_101.setStretch(0, 2)
        self.horizontalLayout_101.setStretch(1, 7)
        self.horizontalLayout_101.setStretch(2, 7)
        self.horizontalLayout_101.setStretch(3, 2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_101)#1
        #############################################################################################################
        #############################################################################################################
        
        
        spacerItem39 = QtWidgets.QSpacerItem(1058, 59, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem39)#6
        
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        spacerItem41 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem41)
        self.back = QtWidgets.QPushButton(self.frame_2)
        self.back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.back.setFont(font)
        self.back.setStyleSheet("QPushButton{\n"
"background:#323232;color:white;border: 2px  solid #757475;"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:lightgray;\n"
"    color:black;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:gray;\n"
"    color:white"
"}\n"
"")
        self.back.setObjectName("back")
        self.horizontalLayout_18.addWidget(self.back)

        spacerItem43 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem43)
        self.start = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start.sizePolicy().hasHeightForWidth())
        self.start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start.setSizePolicy(sizePolicy)
        self.start.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.start.setFont(font)
        self.start.setStyleSheet("QPushButton{\n"
"background:#069CFF;color:black;border: 2px  solid #757475;;"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:lightblue;\n"
"    color:black;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:blue;\n"
"    color:white"
"}\n"
"")
        self.start.setObjectName("start")
        self.horizontalLayout_18.addWidget(self.start)
        spacerItem44 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem44)
        self.horizontalLayout_18.setStretch(0, 40)
        self.horizontalLayout_18.setStretch(1, 1)
        self.horizontalLayout_18.setStretch(2, 2)
        self.horizontalLayout_18.setStretch(3, 4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)#7
        spacerItem45 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem45) #8
        self.verticalLayout_5.setStretch(0, 2)
        self.verticalLayout_5.setStretch(1, 22)
        self.verticalLayout_5.setStretch(2, 22)
        self.verticalLayout_5.setStretch(3, 3)
        self.verticalLayout_5.setStretch(4, 2)
        self.verticalLayout_5.setStretch(5, 2)
        self.horizontalLayout.addWidget(self.frame_2)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 20)
        self.horizontalLayout_11.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 80)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4.setStretch(0, 80)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_6.setIcon(QtGui.QIcon("images/home_white.png"))
        self.pushButton_6.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_8.setIcon(QtGui.QIcon("images/video.png"))
        self.pushButton_8.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_7.setIcon(QtGui.QIcon("images/settings_white.png"))
        self.pushButton_7.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_search.setIcon(QtGui.QIcon("images/search_pls.png"))
        self.pushButton_search.setIconSize(QtCore.QSize(85,85))
        
        self.label_23.setText(_translate("MainWindow", "設定"))
        self.pushButton_2.setText(_translate("MainWindow", "Camera Settings"))
        self.pushButton_0.setText(_translate("MainWindow", "Device Settings"))
        self.pushButton_3.setText(_translate("MainWindow", "功能設定"))
        self.pushButton_4.setText(_translate("MainWindow", "AI Settings"))
        self.pushButton_5.setText(_translate("MainWindow", "Log"))
        self.label_6.setText(_translate("MainWindow", "Camera 1"))
        self.label_15.setText(_translate("MainWindow", "地點"))
        self.place1.setText(_translate("MainWindow", "大門1"))
        self.label_7.setText(_translate("MainWindow", "IP位址"))
        self.ip1.setText(_translate("MainWindow", "192.168.0.53"))
        self.label_8.setText(_translate("MainWindow", "用戶名"))
        self.password1.setText(_translate("MainWindow", "admin"))
        self.label_9.setText(_translate("MainWindow", "密碼"))
        self.password1_2.setText(_translate("MainWindow", "ai123456"))
        self.label_11.setText(_translate("MainWindow", "Camera 2"))
        self.label_19.setText(_translate("MainWindow", "地點"))
        self.place2.setText(_translate("MainWindow", "大門2"))
        self.label_12.setText(_translate("MainWindow", "IP位址"))
        self.ip2.setText(_translate("MainWindow", "192.168.0.142"))
        self.label_13.setText(_translate("MainWindow", "用戶名"))
        self.password3.setText(_translate("MainWindow", "admin"))
        self.label_14.setText(_translate("MainWindow", "密碼"))
        self.password4.setText(_translate("MainWindow", "ai123456"))
        self.back.setText(_translate("MainWindow", " 還原預設值 "))
        self.start.setText(_translate("MainWindow", "確定"))
        self.ROI_onButton.setText(_translate("MainWindow", "On"))
        self.label_ROI.setText(_translate("MainWindow", "ROI: "))
        self.ROI_onButton2.setText(_translate("MainWindow", "On"))
        self.label_ROI2.setText(_translate("MainWindow", "ROI: "))
        self.label_IO.setText(_translate("MainWindow", "Camera: : "))
        self.label_IO_2.setText(_translate("MainWindow", "Camera: : "))
        
        self.label_61.setText(_translate("MainWindow", "Camera 3"))
        self.label_151.setText(_translate("MainWindow", "地點"))
        self.place3.setText(_translate("MainWindow", "大門1"))
        self.label_71.setText(_translate("MainWindow", "IP位址"))
        self.ip3.setText(_translate("MainWindow", "192.168.0.53"))
        self.label_81.setText(_translate("MainWindow", "用戶名"))
        self.password_new1.setText(_translate("MainWindow", "admin"))
        self.label_91.setText(_translate("MainWindow", "密碼"))
        self.password1_new2.setText(_translate("MainWindow", "ai123456"))
        self.label_111.setText(_translate("MainWindow", "Camera 4"))
        self.label_191.setText(_translate("MainWindow", "地點"))
        self.place4.setText(_translate("MainWindow", "大門2"))
        self.label_121.setText(_translate("MainWindow", "IP位址"))
        self.ip4.setText(_translate("MainWindow", "192.168.0.142"))
        self.label_131.setText(_translate("MainWindow", "用戶名"))
        self.password_new3.setText(_translate("MainWindow", "admin"))
        self.label_141.setText(_translate("MainWindow", "密碼"))
        self.password_new4.setText(_translate("MainWindow", "ai123456"))
        
        self.back.setText(_translate("MainWindow", " 還原預設值 "))
        self.start.setText(_translate("MainWindow", "確定"))
        self.ROI_onButton.setText(_translate("MainWindow", "On"))
        self.label_ROI_3.setText(_translate("MainWindow", "ROI: "))
        self.ROI_onButton2.setText(_translate("MainWindow", "On"))
        self.label_ROI2.setText(_translate("MainWindow", "ROI: "))
        self.label_IO.setText(_translate("MainWindow", "Camera: "))
        self.label_IO_2.setText(_translate("MainWindow", "Camera: "))
        
        self.ROI_onButton_3.setText(_translate("MainWindow", "On"))
        self.label_ROI_3.setText(_translate("MainWindow", "ROI: "))
        self.ROI_onButton_4.setText(_translate("MainWindow", "On"))
        self.label_ROI_4.setText(_translate("MainWindow", "ROI: "))
        self.label_IO_3.setText(_translate("MainWindow", "Camera: "))
        self.label_IO_4.setText(_translate("MainWindow", "Camera: "))
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
